import { useEffect, useMemo, useState } from 'react';
import './admin.css';
import AdminSubscriptions from './AdminSubscriptions';
import AdminSupportInbox from './AdminSupportInbox';
import PromotionsAdmin from './PromotionsAdmin';
import AdminZones from './AdminZones';
import {clientOrderId,clientPublicId,dailyPinForProfile,providerMissionId,providerPublicId} from './publicIds';

type Mission={id:string;status:string;category_name?:string;client_name?:string;client_phone?:string;provider_name?:string;provider_id?:string|null;description?:string;created_at:string;client_total_cents?:number|null;payment_status?:string|null};
type Client={id:string;name:string;email?:string;phone?:string;missions_count:number;created_at:string};
type Provider={id:string;name:string;email?:string;phone?:string;status:string;is_online:boolean;category_ids:string[];completed_missions:number;active_missions:number};
type Category={id:string;name:string;hourly_rate_cents:number|null};
type Overview={missions:{total:number;active:number;offered:number;in_progress:number};clients:{total:number};providers:{total:number;online:number;active:number};revenue_cents:number;pending_payouts_cents:number};
type Payment={id:string;mission_id:string;client_name?:string;category_name?:string;amount_cents:number;status:string;payment_method?:string};
type Payout={id:string;mission_id:string;provider_name?:string;category_name?:string;amount_cents:number;status:string;release_at?:string};
const money=(v?:number|null)=>typeof v==='number'?`${(v/100).toFixed(2).replace('.',',')} $`:'—';
const minuteRate=(hourly?:number|null)=>typeof hourly==='number'?hourly/60:null;
const minimum15=(hourly?:number|null)=>typeof hourly==='number'?Math.ceil(hourly*15/60):null;
const statusLabel:Record<string,string>={requested:'À dispatcher',offered:'Offerte',assigned:'Assignée',en_route:'En route',arrived:'Arrivé',in_progress:'En cours',completed:'Terminée',cancelled:'Annulée'};

export default function AdminPortal(){
 const[token,setToken]=useState(sessionStorage.getItem('faislajob_admin_token')||'');const[inputToken,setInputToken]=useState(token);const[tab,setTab]=useState<'dispatch'|'clients'|'providers'|'categories'|'zones'|'promotions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'messages'|'subscriptions'|'finance'>('dispatch');
 const[overview,setOverview]=useState<Overview|null>(null);const[missions,setMissions]=useState<Mission[]>([]);const[clients,setClients]=useState<Client[]>([]);const[providers,setProviders]=useState<Provider[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[payments,setPayments]=useState<Payment[]>([]);const[payouts,setPayouts]=useState<Payout[]>([]);
 const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[selectedMission,setSelectedMission]=useState<Mission|null>(null);const[selectedProvider,setSelectedProvider]=useState('');
 const headers=useMemo(()=>({'x-admin-token':token,'Content-Type':'application/json'}),[token]);
 const api=async(path:string,options:RequestInit={})=>{const r=await fetch(path,{...options,headers:{...headers,...(options.headers as Record<string,string>||{})},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Erreur ${r.status}`);return d};
 const load=async()=>{if(!token)return;setLoading(true);setError('');try{const requests:Promise<any>[]=[api('/api/admin/overview')];if(tab==='dispatch')requests.push(api(`/api/admin/missions?status=${encodeURIComponent(status)}&search=${encodeURIComponent(search)}`),api('/api/admin/providers'));else if(tab==='clients')requests.push(api(`/api/admin/clients?search=${encodeURIComponent(search)}`));else if(tab==='providers')requests.push(api(`/api/admin/providers?search=${encodeURIComponent(search)}`));else if(tab==='categories')requests.push(api('/api/categories'));else if(tab==='zones')requests.push(Promise.resolve({}));else if(tab==='promotions')requests.push(Promise.resolve({}));else requests.push(api('/api/admin/finance'));const data=await Promise.all(requests);setOverview(data[0]);if(tab==='dispatch'){setMissions(data[1].missions);setProviders(data[2].providers)}else if(tab==='clients')setClients(data[1].clients);else if(tab==='providers')setProviders(data[1].providers);else if(tab==='categories')setCategories(data[1].categories);else if(tab==='zones'){}else if(tab==='promotions'){}else{setPayments(data[1].payments);setPayouts(data[1].payouts)}}catch(e){setError(e instanceof Error?e.message:'Erreur admin')}finally{setLoading(false)}};
 useEffect(()=>{load()},[token,tab,status]);useEffect(()=>{if(!token)return;const t=window.setInterval(load,5000);return()=>window.clearInterval(t)},[token,tab,status,search]);
 const login=()=>{sessionStorage.setItem('faislajob_admin_token',inputToken);setToken(inputToken)};const logout=()=>{sessionStorage.removeItem('faislajob_admin_token');setToken('');setInputToken('')};
 const action=async(path:string,body:any={})=>{setLoading(true);setError('');try{await api(path,{method:'POST',body:JSON.stringify(body)});setSelectedMission(null);await load()}catch(e){setError(e instanceof Error?e.message:'Action impossible')}finally{setLoading(false)}};
 const categorySlug=(name:string)=>name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48);
 const parseRate=(value:string)=>Math.round(Number(value.replace(',','.'))*100);
 const addCategory=async()=>{const name=window.prompt('Nom de la nouvelle catégorie');if(!name?.trim())return;const rate=window.prompt('Tarif horaire en dollars','40');if(!rate)return;const cents=parseRate(rate);if(!Number.isFinite(cents)||cents<=0){setError('Tarif horaire invalide');return}await action('/api/admin/categories',{id:categorySlug(name),name:name.trim(),hourlyRateCents:cents})};
 const editCategory=async(c:Category)=>{const name=window.prompt('Nom de la catégorie',c.name);if(!name?.trim())return;const rate=window.prompt('Tarif horaire en dollars',String(((c.hourly_rate_cents||0)/100).toFixed(2)).replace('.',','));if(!rate)return;const cents=parseRate(rate);if(!Number.isFinite(cents)||cents<=0){setError('Tarif horaire invalide');return}await action(`/api/admin/categories/${encodeURIComponent(c.id)}`,{name:name.trim(),hourlyRateCents:cents})};
 const deleteCategory=async(c:Category)=>{if(!window.confirm(`Supprimer la catégorie « ${c.name} »?`))return;await action(`/api/admin/categories/${encodeURIComponent(c.id)}/delete`)};
 const openAssign=(m:Mission)=>{setSelectedMission(m);setSelectedProvider(m.provider_id||'')};
 const pageTitle=tab==='dispatch'?'Centre de dispatch':tab==='clients'?'Clients':tab==='providers'?'Partenaires':tab==='categories'?'Catégories et tarifs':tab==='zones'?'Zones et tarifs':tab==='promotions'?'Promotions et ristournes':tab==='messages'?'Messages clients':tab==='subscriptions'?'Abonnements et récurrence':'Finance';
 if(!token)return <main className="admin-login"><div className="admin-login-card"><div className="admin-logo">FaisLaJob <span>Admin</span></div><h1>Centre des opérations</h1><p>Dispatch, clients, partenaires et finances dans un seul portail.</p><input type="password" placeholder="Clé ADMIN_TOKEN" value={inputToken} onChange={e=>setInputToken(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()}/><button onClick={login}>Ouvrir le portail</button><a href="/">← Retour au site</a></div></main>;
 return <main className="admin-shell"><aside className="admin-sidebar"><div><div className="admin-logo">FaisLaJob <span>Admin</span></div><p className="admin-muted">Centre des opérations</p></div><nav><button className={tab==='dispatch'?'active':''} onClick={()=>setTab('dispatch')}>🚦 Dispatch</button><button className={tab==='clients'?'active':''} onClick={()=>setTab('clients')}>👥 Clients</button><button className={tab==='providers'?'active':''} onClick={()=>setTab('providers')}>🧰 Partenaires</button><button className={tab==='categories'?'active':''} onClick={()=>setTab('categories')}>🏷️ Catégories</button><button className={tab==='zones'?'active':''} onClick={()=>setTab('zones')}>📍 Zones</button><button className={tab==='promotions'?'active':''} onClick={()=>setTab('promotions')}>🎁 Promotions</button><button className={tab==='subscriptions'?'active':''} onClick={()=>setTab('subscriptions')}>🔁 Abonnements</button><button className={tab==='messages'?'active':''} onClick={()=>setTab('messages')}>💬 Messages</button><button className={tab==='finance'?'active':''} onClick={()=>setTab('finance')}>💳 Finance</button></nav><div className="admin-side-bottom"><a href="/">Voir le site</a><button onClick={logout}>Déconnexion admin</button></div></aside>
 <section className="admin-main"><header className="admin-header"><div><div className="admin-eyebrow">Temps réel</div><h1>{pageTitle}</h1></div><button className="admin-refresh" onClick={load}>{loading?'Actualisation…':'↻ Actualiser'}</button></header>{error&&<div className="admin-error">⚠️ {error}</div>}
 {overview&&<div className="admin-kpis"><div><span>Missions actives</span><strong>{overview.missions.active}</strong></div><div><span>Partenaires en ligne</span><strong>{overview.providers.online}</strong></div><div><span>Clients</span><strong>{overview.clients.total}</strong></div><div><span>Revenus encaissés</span><strong>{money(overview.revenue_cents)}</strong></div><div><span>Versements à traiter</span><strong>{money(overview.pending_payouts_cents)}</strong></div></div>}
 {(tab==='dispatch'||tab==='clients'||tab==='providers')&&<div className="admin-tools"><input placeholder="Rechercher nom, téléphone, # mission…" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><button onClick={load}>Rechercher</button>{tab==='dispatch'&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option><option value="requested">À dispatcher</option><option value="offered">Offerte</option><option value="assigned">Assignée</option><option value="en_route">En route</option><option value="arrived">Arrivé</option><option value="in_progress">En cours</option><option value="completed">Terminée</option><option value="cancelled">Annulée</option></select>}</div>}
 {tab==='dispatch'&&<div className="admin-grid">{missions.map(m=><article className="admin-card mission-card" key={m.id}><div className="admin-card-top"><div><span className="mission-number">Commande client #{clientOrderId(m.id)} · Mission partenaire #{providerMissionId(m.id)}</span><h3>{m.category_name||'Service'}</h3></div><span className={`status status-${m.status}`}>{statusLabel[m.status]||m.status}</span></div><div className="mission-people"><div><small>Client</small><strong>{m.client_name||'—'}</strong><span>{m.client_phone||''}</span></div><div><small>Partenaire</small><strong>{m.provider_name||'Non assigné'}</strong></div></div><p className="mission-desc">{m.description}</p><div className="mission-meta"><span>Interne #{m.id} · {new Date(m.created_at).toLocaleString('fr-CA')}</span>{m.client_total_cents?<strong>{money(m.client_total_cents)}</strong>:null}</div>{!['completed','cancelled'].includes(m.status)&&<div className="admin-actions"><button onClick={()=>openAssign(m)}>Assigner</button><button onClick={()=>action(`/api/admin/missions/${m.id}/redispatch`)}>Redispatch</button><button className="danger" onClick={()=>confirm(`Annuler commande #${clientOrderId(m.id)}?`)&&action(`/api/admin/missions/${m.id}/cancel`)}>Annuler</button></div>}</article>)}{missions.length===0&&<div className="admin-empty">Aucune mission trouvée.</div>}</div>}
 {tab==='clients'&&<div className="admin-table-wrap"><table><thead><tr><th>Client</th><th>Contact</th><th>Vérification</th><th>Commandes</th><th>Créé</th></tr></thead><tbody>{clients.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>ID {clientPublicId(c.id)}</small></td><td>{c.phone||'—'}<small>{c.email||''}</small></td><td><strong>NIP {dailyPinForProfile('client',c.id)}</strong><small>change chaque jour</small></td><td>{c.missions_count}</td><td>{new Date(c.created_at).toLocaleDateString('fr-CA')}</td></tr>)}</tbody></table></div>}
 {tab==='providers'&&<div className="admin-grid">{providers.map(p=><article className="admin-card" key={p.id}><div className="admin-card-top"><div><span className="mission-number">Partenaire #{providerPublicId(p.id)}</span><h3>{p.name}</h3></div><span className={`online-dot ${p.is_online?'on':''}`}>{p.is_online?'● En ligne':'○ Hors ligne'}</span></div><p>{p.phone||'—'}<br/><span className="admin-muted">{p.email||''}</span></p><div className="provider-stats"><span>NIP du jour <strong>{dailyPinForProfile('provider',p.id)}</strong></span><span>{p.completed_missions} terminées</span><span>{p.active_missions} actives</span></div><div className="category-chips">{(p.category_ids||[]).map(c=><span key={c}>{c}</span>)}</div><div className="admin-actions"><button onClick={()=>action(`/api/admin/providers/${p.id}/online`,{online:!p.is_online})}>{p.is_online?'Mettre hors ligne':'Mettre en ligne'}</button>{p.status==='active'?<button className="danger" onClick={()=>action(`/api/admin/providers/${p.id}/status`,{status:'suspended'})}>Suspendre</button>:<button onClick={()=>action(`/api/admin/providers/${p.id}/status`,{status:'active'})}>Réactiver</button>}</div></article>)}</div>}
 {tab==='categories'&&<><div className="admin-card"><div className="admin-card-top"><div><span className="mission-number">Tarification client</span><h3>Minimum facturable : 15 minutes</h3></div><div className="admin-actions"><button onClick={addCategory}>＋ Ajouter une catégorie</button></div></div><p className="admin-muted">Modifie le tarif horaire ici. Le tarif à la minute et le minimum 15 minutes sont recalculés automatiquement et affichés au client.</p></div><div className="admin-table-wrap"><table><thead><tr><th>Catégorie</th><th>Tarif / minute</th><th>Tarif / heure</th><th>Minimum 15 min</th><th>Actions</th></tr></thead><tbody>{categories.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.id}</small></td><td><strong>{money(minuteRate(c.hourly_rate_cents))}</strong></td><td><strong>{money(c.hourly_rate_cents)}</strong></td><td><strong>{money(minimum15(c.hourly_rate_cents))}</strong></td><td><div className="admin-actions"><button onClick={()=>editCategory(c)}>Modifier</button><button className="danger" onClick={()=>deleteCategory(c)}>Supprimer</button></div></td></tr>)}</tbody></table></div></>}
 {tab==='zones'&&<AdminZones token={token}/>}
 {tab==='promotions'&&<PromotionsAdmin token={token}/>}
 {tab==='messages'&&<AdminSupportInbox token={token}/>}
 {tab==='subscriptions'&&<AdminSubscriptions token={token}/>}
 {tab==='finance'&&<><h2 className="admin-section-title">Paiements clients</h2><div className="admin-table-wrap"><table><thead><tr><th>Commande</th><th>Client</th><th>Montant</th><th>Statut</th><th>Méthode</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>#{clientOrderId(p.mission_id)}<small>{p.category_name}</small></td><td>{p.client_name||'—'}</td><td><strong>{money(p.amount_cents)}</strong></td><td>{p.status}</td><td>{p.payment_method||'—'}</td></tr>)}</tbody></table></div><h2 className="admin-section-title">Versements partenaires</h2><div className="admin-table-wrap"><table><thead><tr><th>Mission</th><th>Partenaire</th><th>Montant</th><th>Statut</th><th>Action</th></tr></thead><tbody>{payouts.map(p=><tr key={p.id}><td>#{providerMissionId(p.mission_id)}<small>{p.category_name}</small></td><td>{p.provider_name}</td><td><strong>{money(p.amount_cents)}</strong></td><td>{p.status}</td><td><select value={p.status} onChange={e=>action(`/api/admin/payouts/${p.id}/status`,{status:e.target.value})}><option value="waiting_payment">En attente</option><option value="holding">Retenue</option><option value="ready">Prêt à payer</option><option value="paid">Payé</option><option value="blocked">Bloqué</option></select></td></tr>)}</tbody></table></div></>}
 </section>{selectedMission&&<div className="admin-modal-backdrop" onClick={()=>setSelectedMission(null)}><div className="admin-modal" onClick={e=>e.stopPropagation()}><div className="admin-eyebrow">Mission #{providerMissionId(selectedMission.id)} · commande #{clientOrderId(selectedMission.id)}</div><h2>Assigner un partenaire</h2><select value={selectedProvider} onChange={e=>setSelectedProvider(e.target.value)}><option value="">Choisir…</option>{providers.filter(p=>p.status==='active').map(p=><option value={p.id} key={p.id}>{p.is_online?'🟢':'⚪'} {p.name} — #{providerPublicId(p.id)}</option>)}</select><div className="admin-actions"><button disabled={!selectedProvider} onClick={()=>action(`/api/admin/missions/${selectedMission.id}/assign`,{providerId:Number(selectedProvider)})}>Confirmer l’assignation</button><button onClick={()=>setSelectedMission(null)}>Fermer</button></div></div></div>}</main>
}
