import { useEffect, useMemo, useState } from 'react';
import './admin.css';

type Mission={id:string;status:string;category_name?:string;client_name?:string;client_phone?:string;provider_name?:string;provider_id?:string|null;description?:string;created_at:string;client_total_cents?:number|null;payment_status?:string|null};
type Client={id:string;name:string;email?:string;phone?:string;missions_count:number;created_at:string};
type Provider={id:string;name:string;email?:string;phone?:string;status:string;is_online:boolean;category_ids:string[];completed_missions:number;active_missions:number};
type Overview={missions:{total:number;active:number;offered:number;in_progress:number};clients:{total:number};providers:{total:number;online:number;active:number};revenue_cents:number;pending_payouts_cents:number};
type Payment={id:string;mission_id:string;client_name?:string;category_name?:string;amount_cents:number;status:string;payment_method?:string};
type Payout={id:string;mission_id:string;provider_name?:string;category_name?:string;amount_cents:number;status:string;release_at?:string};

const money=(v?:number|null)=>typeof v==='number'?`${(v/100).toFixed(2).replace('.',',')} $`:'—';
const statusLabel:Record<string,string>={requested:'À dispatcher',offered:'Offerte',assigned:'Assignée',en_route:'En route',arrived:'Arrivé',in_progress:'En cours',completed:'Terminée',cancelled:'Annulée'};

export default function AdminPortal(){
 const [token,setToken]=useState(sessionStorage.getItem('faislajob_admin_token')||'');
 const [inputToken,setInputToken]=useState(token);
 const [tab,setTab]=useState<'dispatch'|'clients'|'providers'|'finance'>('dispatch');
 const [overview,setOverview]=useState<Overview|null>(null);const[missions,setMissions]=useState<Mission[]>([]);const[clients,setClients]=useState<Client[]>([]);const[providers,setProviders]=useState<Provider[]>([]);const[payments,setPayments]=useState<Payment[]>([]);const[payouts,setPayouts]=useState<Payout[]>([]);
 const [search,setSearch]=useState('');const[status,setStatus]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[selectedMission,setSelectedMission]=useState<Mission|null>(null);const[selectedProvider,setSelectedProvider]=useState('');
 const headers=useMemo(()=>({'x-admin-token':token,'Content-Type':'application/json'}),[token]);
 const api=async(path:string,options:RequestInit={})=>{const r=await fetch(path,{...options,headers:{...headers,...(options.headers||{})},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Erreur ${r.status}`);return d};
 const load=async()=>{if(!token)return;setLoading(true);setError('');try{const o=await api('/api/admin/overview');setOverview(o);if(tab==='dispatch'){const d=await api(`/api/admin/missions?status=${encodeURIComponent(status)}&search=${encodeURIComponent(search)}`);setMissions(d.missions)}if(tab==='clients'){const d=await api(`/api/admin/clients?search=${encodeURIComponent(search)}`);setClients(d.clients)}if(tab==='providers'){const d=await api(`/api/admin/providers?search=${encodeURIComponent(search)}`);setProviders(d.providers)}if(tab==='finance'){const d=await api('/api/admin/finance');setPayments(d.payments);setPayouts(d.payouts)}}catch(e){setError(e instanceof Error?e.message:'Erreur admin')}finally{setLoading(false)}};
 useEffect(()=>{load()},[token,tab,status]);
 useEffect(()=>{if(!token)return;const t=window.setInterval(load,5000);return()=>window.clearInterval(t)},[token,tab,status,search]);
 const login=()=>{sessionStorage.setItem('faislajob_admin_token',inputToken);setToken(inputToken)};
 const logout=()=>{sessionStorage.removeItem('faislajob_admin_token');setToken('');setInputToken('')};
 const action=async(path:string,body:any={})=>{setLoading(true);setError('');try{await api(path,{method:'POST',body:JSON.stringify(body)});setSelectedMission(null);await load()}catch(e){setError(e instanceof Error?e.message:'Action impossible')}finally{setLoading(false)}};
 const openAssign=(m:Mission)=>{setSelectedMission(m);setSelectedProvider(m.provider_id||'')};
 if(!token)return <main className="admin-login"><div className="admin-login-card"><div className="admin-logo">FaisLaJob <span>Admin</span></div><h1>Centre des opérations</h1><p>Dispatch, clients, partenaires et finances dans un seul portail.</p><input type="password" placeholder="Clé ADMIN_TOKEN" value={inputToken} onChange={e=>setInputToken(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()}/><button onClick={login}>Ouvrir le portail</button><a href="/">← Retour au site</a></div></main>;
 return <main className="admin-shell">
  <aside className="admin-sidebar"><div><div className="admin-logo">FaisLaJob <span>Admin</span></div><p className="admin-muted">Centre des opérations</p></div><nav><button className={tab==='dispatch'?'active':''} onClick={()=>setTab('dispatch')}>🚦 Dispatch</button><button className={tab==='clients'?'active':''} onClick={()=>setTab('clients')}>👥 Clients</button><button className={tab==='providers'?'active':''} onClick={()=>setTab('providers')}>🧰 Partenaires</button><button className={tab==='finance'?'active':''} onClick={()=>setTab('finance')}>💳 Finance</button></nav><div className="admin-side-bottom"><a href="/">Voir le site</a><button onClick={logout}>Déconnexion admin</button></div></aside>
  <section className="admin-main"><header className="admin-header"><div><div className="admin-eyebrow">Temps réel</div><h1>{tab==='dispatch'?'Centre de dispatch':tab==='clients'?'Clients':tab==='providers'?'Partenaires':'Finance'}</h1></div><button className="admin-refresh" onClick={load}>{loading?'Actualisation…':'↻ Actualiser'}</button></header>
  {error&&<div className="admin-error">⚠️ {error}</div>}
  {overview&&<div className="admin-kpis"><div><span>Missions actives</span><strong>{overview.missions.active}</strong></div><div><span>Partenaires en ligne</span><strong>{overview.providers.online}</strong></div><div><span>Clients</span><strong>{overview.clients.total}</strong></div><div><span>Revenus encaissés</span><strong>{money(overview.revenue_cents)}</strong></div><div><span>Versements à traiter</span><strong>{money(overview.pending_payouts_cents)}</strong></div></div>}
  {(tab==='dispatch'||tab==='clients'||tab==='providers')&&<div className="admin-tools"><input placeholder="Rechercher nom, téléphone, # mission…" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><button onClick={load}>Rechercher</button>{tab==='dispatch'&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option><option value="requested">À dispatcher</option><option value="offered">Offerte</option><option value="assigned">Assignée</option><option value="en_route">En route</option><option value="arrived">Arrivé</option><option value="in_progress">En cours</option><option value="completed">Terminée</option><option value="cancelled">Annulée</option></select>}</div>}
  {tab==='dispatch'&&<div className="admin-grid">{missions.map(m=><article className="admin-card mission-card" key={m.id}><div className="admin-card-top"><div><span className="mission-number">Mission #{m.id}</span><h3>{m.category_name||'Service'}</h3></div><span className={`status status-${m.status}`}>{statusLabel[m.status]||m.status}</span></div><div className="mission-people"><div><small>Client</small><strong>{m.client_name||'—'}</strong><span>{m.client_phone||''}</span></div><div><small>Partenaire</small><strong>{m.provider_name||'Non assigné'}</strong></div></div><p className="mission-desc">{m.description}</p><div className="mission-meta"><span>{new Date(m.created_at).toLocaleString('fr-CA')}</span>{m.client_total_cents?<strong>{money(m.client_total_cents)}</strong>:null}</div>{!['completed','cancelled'].includes(m.status)&&<div className="admin-actions"><button onClick={()=>openAssign(m)}>Assigner</button><button onClick={()=>action(`/api/admin/missions/${m.id}/redispatch`)}>Redispatch</button><button className="danger" onClick={()=>confirm(`Annuler mission #${m.id}?`)&&action(`/api/admin/missions/${m.id}/cancel`)}>Annuler</button></div>}</article>)}{missions.length===0&&<div className="admin-empty">Aucune mission trouvée.</div>}</div>}
  {tab==='clients'&&<div className="admin-table-wrap"><table><thead><tr><th>Client</th><th>Contact</th><th>Missions</th><th>Créé</th></tr></thead><tbody>{clients.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>#{c.id}</small></td><td>{c.phone||'—'}<small>{c.email||''}</small></td><td>{c.missions_count}</td><td>{new Date(c.created_at).toLocaleDateString('fr-CA')}</td></tr>)}</tbody></table></div>}
  {tab==='providers'&&<div className="admin-grid">{providers.map(p=><article className="admin-card" key={p.id}><div className="admin-card-top"><div><span className="mission-number">Partenaire #{p.id}</span><h3>{p.name}</h3></div><span className={`online-dot ${p.is_online?'on':''}`}>{p.is_online?'● En ligne':'○ Hors ligne'}</span></div><p>{p.phone||'—'}<br/><span className="admin-muted">{p.email||''}</span></p><div className="provider-stats"><span>{p.completed_missions} terminées</span><span>{p.active_missions} actives</span></div><div className="category-chips">{(p.category_ids||[]).map(c=><span key={c}>{c}</span>)}</div><div className="admin-actions"><button onClick={()=>action(`/api/admin/providers/${p.id}/online`,{online:!p.is_online})}>{p.is_online?'Mettre hors ligne':'Mettre en ligne'}</button>{p.status==='active'?<button className="danger" onClick={()=>action(`/api/admin/providers/${p.id}/status`,{status:'suspended'})}>Suspendre</button>:<button onClick={()=>action(`/api/admin/providers/${p.id}/status`,{status:'active'})}>Réactiver</button>}</div></article>)}</div>}
  {tab==='finance'&&<><h2 className="admin-section-title">Paiements clients</h2><div className="admin-table-wrap"><table><thead><tr><th>Mission</th><th>Client</th><th>Montant</th><th>Statut</th><th>Méthode</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>#{p.mission_id}<small>{p.category_name}</small></td><td>{p.client_name||'—'}</td><td><strong>{money(p.amount_cents)}</strong></td><td>{p.status}</td><td>{p.payment_method||'—'}</td></tr>)}</tbody></table></div><h2 className="admin-section-title">Versements partenaires</h2><div className="admin-table-wrap"><table><thead><tr><th>Mission</th><th>Partenaire</th><th>Montant</th><th>Statut</th><th>Action</th></tr></thead><tbody>{payouts.map(p=><tr key={p.id}><td>#{p.mission_id}<small>{p.category_name}</small></td><td>{p.provider_name}</td><td><strong>{money(p.amount_cents)}</strong></td><td>{p.status}</td><td><select value={p.status} onChange={e=>action(`/api/admin/payouts/${p.id}/status`,{status:e.target.value})}><option value="waiting_payment">En attente</option><option value="holding">Retenue</option><option value="ready">Prêt à payer</option><option value="paid">Payé</option><option value="blocked">Bloqué</option></select></td></tr>)}</tbody></table></div></>}
  </section>
  {selectedMission&&<div className="admin-modal-backdrop" onClick={()=>setSelectedMission(null)}><div className="admin-modal" onClick={e=>e.stopPropagation()}><div className="admin-eyebrow">Mission #{selectedMission.id}</div><h2>Assigner un partenaire</h2><select value={selectedProvider} onChange={e=>setSelectedProvider(e.target.value)}><option value="">Choisir…</option>{providers.filter(p=>p.status==='active').map(p=><option value={p.id} key={p.id}>{p.is_online?'🟢':'⚪'} {p.name} — #{p.id}</option>)}</select><div className="admin-actions"><button disabled={!selectedProvider} onClick={()=>action(`/api/admin/missions/${selectedMission.id}/assign`,{providerId:Number(selectedProvider)})}>Confirmer l’assignation</button><button onClick={()=>setSelectedMission(null)}>Fermer</button></div></div></div>}
 </main>
}
