import {useEffect,useMemo,useState} from 'react';
import './subscriptions.css';

type Category={id:string;name:string};
type Plan={id:string;category_id:string;category_name:string;name:string;description?:string|null;trigger_type:'snow_accumulation'|'weekly'|'interval'|'manual';trigger_config:any;pricing_type:'per_minute'|'per_visit'|'monthly'|'seasonal';price_cents:number;same_team:boolean;max_interventions?:number|null;active:boolean;starts_at?:string|null;ends_at?:string|null;subscribers?:number};
type Form={categoryId:string;name:string;description:string;triggerType:Plan['trigger_type'];thresholds:string;visitsPerWeek:string;intervalDays:string;pricingType:Plan['pricing_type'];price:string;sameTeam:boolean;maxInterventions:string;startsAt:string;endsAt:string};
const empty:Form={categoryId:'',name:'',description:'',triggerType:'weekly',thresholds:'5, 15, 25, 35',visitsPerWeek:'1',intervalDays:'7',pricingType:'per_minute',price:'',sameTeam:false,maxInterventions:'',startsAt:'',endsAt:''};
const money=(c:number)=>`${(Number(c||0)/100).toFixed(2).replace('.',',')} $`;
const minuteMoney=(hourly:number)=>money(hourly/60);
const minimum15=(hourly:number)=>money(Math.ceil(hourly*15/60));

export default function AdminSubscriptions({token}:{token:string}){
 const[plans,setPlans]=useState<Plan[]>([]),[categories,setCategories]=useState<Category[]>([]),[form,setForm]=useState<Form>(empty),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showForm,setShowForm]=useState(false);
 const headers=useMemo(()=>({'x-admin-token':token,'Content-Type':'application/json'}),[token]);
 const load=async()=>{try{const[pr,cr]=await Promise.all([fetch('/api/admin/service-plans',{headers,cache:'no-store'}),fetch('/api/categories',{cache:'no-store'})]);const pd=await pr.json(),cd=await cr.json();if(!pr.ok)throw new Error(pd.error||'Impossible de charger les abonnements');setPlans(pd.plans||[]);setCategories(cd.categories||[])}catch(e){setError(e instanceof Error?e.message:'Erreur')}};
 useEffect(()=>{load()},[token]);
 const triggerLabel=(p:Plan)=>p.trigger_type==='snow_accumulation'?`Neige : ${(p.trigger_config?.thresholds_cm||[]).join(' / ')} cm`:p.trigger_type==='weekly'?`${p.trigger_config?.visits_per_week||1}× par semaine`:p.trigger_type==='interval'?`Tous les ${p.trigger_config?.interval_days||7} jours`:'Déclenchement manuel';
 const priceLabel=(p:Plan)=>p.pricing_type==='per_minute'?`${minuteMoney(p.price_cents)}/min · ${money(p.price_cents)}/h · min. 15 min ${minimum15(p.price_cents)}`:`${money(p.price_cents)} ${p.pricing_type==='per_visit'?'par intervention':p.pricing_type==='monthly'?'par mois':'par saison'}`;
 const startCreate=()=>{setEditing(null);setForm({...empty,categoryId:categories[0]?.id||''});setShowForm(true);setError('')};
 const startEdit=(p:Plan)=>{setEditing(p.id);setForm({categoryId:p.category_id,name:p.name,description:p.description||'',triggerType:p.trigger_type,thresholds:(p.trigger_config?.thresholds_cm||[]).join(', '),visitsPerWeek:String(p.trigger_config?.visits_per_week||1),intervalDays:String(p.trigger_config?.interval_days||7),pricingType:p.pricing_type,price:String((p.price_cents||0)/100).replace('.',','),sameTeam:Boolean(p.same_team),maxInterventions:p.max_interventions?String(p.max_interventions):'',startsAt:p.starts_at?p.starts_at.slice(0,10):'',endsAt:p.ends_at?p.ends_at.slice(0,10):''});setShowForm(true);setError('')};
 const save=async()=>{setBusy(true);setError('');try{if(!form.categoryId||!form.name.trim())throw new Error('Choisis une catégorie et donne un nom au plan.');const price=Number(form.price.replace(',','.'));if(!Number.isFinite(price)||price<0)throw new Error('Prix invalide.');let triggerConfig:any={};if(form.triggerType==='snow_accumulation'){const thresholds=form.thresholds.split(/[;, ]+/).map(Number).filter(n=>Number.isFinite(n)&&n>0);if(!thresholds.length)throw new Error('Entre au moins un seuil de neige, par exemple 5, 15, 25, 35.');triggerConfig={thresholds_cm:thresholds}}else if(form.triggerType==='weekly'){triggerConfig={visits_per_week:Math.max(1,Math.min(7,Number(form.visitsPerWeek)||1))}}else if(form.triggerType==='interval'){triggerConfig={interval_days:Math.max(1,Number(form.intervalDays)||7)}}const body={categoryId:form.categoryId,name:form.name.trim(),description:form.description.trim(),triggerType:form.triggerType,triggerConfig,pricingType:form.pricingType,priceCents:Math.round(price*100),sameTeam:form.sameTeam,maxInterventions:form.maxInterventions?Number(form.maxInterventions):null,startsAt:form.startsAt||null,endsAt:form.endsAt||null};const r=await fetch(editing?`/api/admin/service-plans/${editing}`:'/api/admin/service-plans',{method:'POST',headers,body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Enregistrement impossible');setShowForm(false);setEditing(null);setForm(empty);await load()}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setBusy(false)}};
 const toggle=async(p:Plan)=>{await fetch(`/api/admin/service-plans/${p.id}/toggle`,{method:'POST',headers,body:JSON.stringify({active:!p.active})});await load()};
 const remove=async(p:Plan)=>{if(!confirm(`Supprimer « ${p.name} »?`))return;const r=await fetch(`/api/admin/service-plans/${p.id}/delete`,{method:'POST',headers});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Suppression impossible');return}await load()};
 const pricePreview=()=>{const cents=Math.max(0,Math.round((Number(form.price.replace(',','.'))||0)*100));if(form.pricingType==='per_minute')return `${minuteMoney(cents)}/min · ${money(cents)}/h · minimum 15 min ${minimum15(cents)}`;return `${form.price||'0'} $ ${form.pricingType==='per_visit'?'par intervention':form.pricingType==='monthly'?'par mois':'par saison'}`};
 return <div className="subs-admin">
  <div className="admin-card"><div className="admin-card-top"><div><span className="mission-number">Services récurrents</span><h3>Abonnements et interventions automatiques</h3></div><div className="admin-actions"><button onClick={startCreate}>＋ Créer un abonnement</button></div></div><p className="admin-muted">Crée des plans comme « Déneigement 5/15/25/35 cm » ou « Litière 2× par semaine ». Les plans actifs apparaissent automatiquement en haut de la catégorie côté client.</p></div>
  {error&&<div className="admin-error">⚠️ {error}</div>}
  {showForm&&<section className="subs-form admin-card"><div className="subs-form-head"><div><span className="mission-number">{editing?'Modifier le plan':'Nouveau plan'}</span><h3>{editing?'Modifier l’abonnement':'Créer un abonnement'}</h3></div><button className="portal-secondary" onClick={()=>setShowForm(false)}>Fermer</button></div>
   <div className="subs-form-grid"><label><span>1. Catégorie</span><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Choisir…</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>Nom du plan</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex. Déneigement automatique"/></label><label className="wide"><span>Description visible au client</span><textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Ex. Une équipe intervient à chaque palier d’accumulation."/></label></div>
   <div className="subs-step"><h4>2. Quand faut-il déclencher une intervention?</h4><div className="subs-choice-grid">{([['snow_accumulation','❄️ Selon accumulation de neige'],['weekly','📅 Chaque semaine'],['interval','🔁 Tous les X jours'],['manual','✋ Manuellement']] as const).map(([id,label])=><button key={id} className={form.triggerType===id?'selected':''} onClick={()=>setForm({...form,triggerType:id})}>{label}</button>)}</div>{form.triggerType==='snow_accumulation'&&<label className="subs-inline-field"><span>Seuils en cm</span><input value={form.thresholds} onChange={e=>setForm({...form,thresholds:e.target.value})} placeholder="5, 15, 25, 35"/><small>Ex. 5, 15, 25, 35 = jusqu’à 4 interventions si la bordée atteint 35 cm.</small></label>}{form.triggerType==='weekly'&&<label className="subs-inline-field"><span>Nombre de visites par semaine</span><select value={form.visitsPerWeek} onChange={e=>setForm({...form,visitsPerWeek:e.target.value})}>{[1,2,3,4,5,6,7].map(n=><option key={n} value={n}>{n}× par semaine</option>)}</select></label>}{form.triggerType==='interval'&&<label className="subs-inline-field"><span>Intervalle</span><input type="number" min="1" value={form.intervalDays} onChange={e=>setForm({...form,intervalDays:e.target.value})}/><small>Nombre de jours entre chaque intervention.</small></label>}</div>
   <div className="subs-step"><h4>3. Prix</h4><div className="subs-form-grid"><label><span>Facturation</span><select value={form.pricingType} onChange={e=>setForm({...form,pricingType:e.target.value as Form['pricingType']})}><option value="per_minute">À la minute (comme une mission régulière)</option><option value="per_visit">Par intervention</option><option value="monthly">Forfait mensuel</option><option value="seasonal">Forfait saisonnier</option></select></label><label><span>{form.pricingType==='per_minute'?'Tarif horaire ($)':'Prix ($)'}</span><input inputMode="decimal" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder={form.pricingType==='per_minute'?'Ex. 40,00':'Ex. 25,00'}/>{form.pricingType==='per_minute'&&<small>Le tarif à la minute et le minimum de 15 minutes sont calculés automatiquement.</small>}</label></div></div>
   <div className="subs-step"><h4>4. Options</h4><div className="subs-form-grid"><label className="subs-check"><input type="checkbox" checked={form.sameTeam} onChange={e=>setForm({...form,sameTeam:e.target.checked})}/><span>Toujours privilégier la même équipe</span></label><label><span>Maximum d’interventions <small>(facultatif)</small></span><input type="number" min="1" value={form.maxInterventions} onChange={e=>setForm({...form,maxInterventions:e.target.value})} placeholder="Illimité"/></label><label><span>Date de début <small>(facultatif)</small></span><input type="date" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label><span>Date de fin <small>(facultatif)</small></span><input type="date" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label></div></div>
   <div className="subs-preview"><span>Aperçu</span><strong>{form.name||'Nom de l’abonnement'}</strong><p>{form.triggerType==='snow_accumulation'?`Intervention aux seuils ${form.thresholds||'—'} cm`:form.triggerType==='weekly'?`${form.visitsPerWeek}× par semaine`:form.triggerType==='interval'?`Tous les ${form.intervalDays} jours`:'Déclenchement manuel'} • {pricePreview()}</p></div>
   <div className="admin-actions"><button disabled={busy} onClick={save}>{busy?'Enregistrement…':'✓ Enregistrer le plan'}</button><button onClick={()=>setShowForm(false)}>Annuler</button></div>
  </section>}
  <div className="subs-plan-grid">{plans.map(p=><article className={`subs-plan-card ${p.active?'':'inactive'}`} key={p.id}><div className="subs-plan-top"><div><span className="mission-number">{p.category_name}</span><h3>{p.name}</h3></div><span className={p.active?'online-dot on':'online-dot'}>{p.active?'● Actif':'○ Inactif'}</span></div><p>{p.description||'Aucune description'}</p><div className="subs-plan-facts"><span><b>Déclenchement</b>{triggerLabel(p)}</span><span><b>Prix</b>{priceLabel(p)}</span><span><b>Clients abonnés</b>{p.subscribers||0}</span><span><b>Équipe</b>{p.same_team?'Même équipe privilégiée':'Équipe disponible'}</span></div><div className="admin-actions"><button onClick={()=>startEdit(p)}>Modifier</button><button onClick={()=>toggle(p)}>{p.active?'Désactiver':'Activer'}</button><button className="danger" onClick={()=>remove(p)}>Supprimer</button></div></article>)}{plans.length===0&&<div className="admin-empty">Aucun abonnement créé pour le moment.</div>}</div>
 </div>;
}
