import {useEffect,useRef,useState} from 'react';
import './support-messages.css';

type Thread={id:string;client_id:string;client_name:string;client_email?:string;client_phone?:string;status:string;unread_count:number;last_message?:string|null;last_message_at?:string|null};
type Message={id:string;sender_type:'client'|'admin';body:string;created_at:string;read_at?:string|null};

export default function AdminSupportInbox({token}:{token:string}){
 const[threads,setThreads]=useState<Thread[]>([]),[selected,setSelected]=useState<Thread|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false);const endRef=useRef<HTMLDivElement|null>(null);
 const headers={'x-admin-token':token,'Content-Type':'application/json'};
 const loadThreads=async()=>{try{const r=await fetch('/api/admin/support/threads',{headers,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Impossible de charger les conversations');setThreads(d.threads||[]);if(selected){const fresh=(d.threads||[]).find((t:Thread)=>String(t.id)===String(selected.id));if(fresh)setSelected(fresh)}}catch(e){setError(e instanceof Error?e.message:'Erreur')}};
 const openThread=async(t:Thread,background=false)=>{try{const r=await fetch(`/api/admin/support/threads/${t.id}`,{headers,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Conversation introuvable');setSelected({...t,...d.thread});setMessages(d.messages||[]);if(!background)setError('');await loadThreads()}catch(e){if(!background)setError(e instanceof Error?e.message:'Erreur')}};
 useEffect(()=>{loadThreads();const timer=window.setInterval(async()=>{await loadThreads();if(selected)await openThread(selected,true)},3000);return()=>window.clearInterval(timer)},[token,selected?.id]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length]);
 const send=async()=>{const body=text.trim();if(!selected||!body||sending)return;setSending(true);try{const r=await fetch(`/api/admin/support/threads/${selected.id}/messages`,{method:'POST',headers,body:JSON.stringify({body})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Envoi impossible');setText('');await openThread(selected,true)}catch(e){setError(e instanceof Error?e.message:'Envoi impossible')}finally{setSending(false)}};
 const toggleClosed=async()=>{if(!selected)return;const status=selected.status==='closed'?'open':'closed';await fetch(`/api/admin/support/threads/${selected.id}/status`,{method:'POST',headers,body:JSON.stringify({status})});setSelected({...selected,status});await loadThreads()};
 return <div className="admin-support-layout"><aside className="admin-support-list"><div className="admin-support-title"><div><span>Boîte de réception</span><h2>Messages clients</h2></div><button onClick={loadThreads}>↻</button></div>{error&&<div className="support-chat-error">⚠️ {error}</div>}{threads.length===0?<div className="admin-support-empty">📭 Aucun message client.</div>:threads.map(t=><button key={t.id} className={`admin-thread-card ${selected?.id===t.id?'active':''}`} onClick={()=>openThread(t)}><div className="admin-thread-avatar">{t.client_name?.[0]?.toUpperCase()||'C'}</div><div><strong>{t.client_name}</strong><span>{t.last_message||'Nouvelle conversation'}</span><small>{t.last_message_at?new Date(t.last_message_at).toLocaleString('fr-CA',{dateStyle:'short',timeStyle:'short'}):''}</small></div>{Number(t.unread_count)>0&&<b className="admin-thread-badge">{t.unread_count>99?'99+':t.unread_count}</b>}</button>)}</aside><section className="admin-support-chat">{!selected?<div className="admin-support-placeholder"><div>💬</div><h2>Choisis une conversation</h2><p>Les messages du client apparaîtront ici.</p></div>:<><div className="admin-support-chat-head"><div><span>Client</span><h2>{selected.client_name}</h2><p>{selected.client_email||''}{selected.client_phone?` • ${selected.client_phone}`:''}</p></div><button onClick={toggleClosed}>{selected.status==='closed'?'Rouvrir':'Fermer la conversation'}</button></div><div className="support-chat-body admin-chat-body">{messages.map(m=><div key={m.id} className={`support-bubble-row ${m.sender_type==='admin'?'mine':'theirs'}`}><div className="support-bubble"><small>{m.sender_type==='admin'?'FaisLaJob':'Client'}</small><p>{m.body}</p><time>{new Date(m.created_at).toLocaleString('fr-CA',{dateStyle:'short',timeStyle:'short'})}</time></div></div>)}<div ref={endRef}/></div><div className="support-compose"><textarea rows={2} value={text} placeholder="Répondre au client…" maxLength={4000} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button onClick={send} disabled={!text.trim()||sending||selected.status==='closed'}>{sending?'Envoi…':'Répondre ➤'}</button></div></>}</section></div>
}
