import { useEffect, useState } from 'react';

type Rate={category_id:string;category_name:string;default_hourly_rate_cents:number|null;hourly_rate_cents:number|null};
type Zone={id:string;name:string;city_match:string;is_active:boolean;latitude:number|null;longitude:number|null;radius_km:number|null;rates:Rate[]};
type Place={lat:string;lon:string;display_name:string};

const money=(cents:number|null|undefined)=>typeof cents==='number'?`${(cents/100).toFixed(2).replace('.',',')} $`:'—';

export default function AdminZones({token}:{token:string}){
 const[zones,setZones]=useState<Zone[]>([]),[name,setName]=useState(''),[city,setCity]=useState(''),[radius,setRadius]=useState('25'),[error,setError]=useState(''),[saving,setSaving]=useState(false),[locatingId,setLocatingId]=useState<string|null>(null);
 const headers={'x-admin-token':token,'Content-Type':'application/json'};
 const api=async(path:string,options:RequestInit={})=>{const r=await fetch(path,{...options,headers:{...headers,...(options.headers as Record<string,string>||{})},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Erreur ${r.status}`);return d};
 const load=async()=>{try{const d=await api('/api/admin/zones');setZones(d.zones||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Erreur')}};
 useEffect(()=>{load()},[]);
 const geocode=async(value:string)=>{const params=new URLSearchParams({format:'jsonv2',countrycodes:'ca',limit:'1',q:`${value}, Québec, Canada`});const r=await fetch(`https://nominatim.openstreetmap.org/search?${params.toString()}`,{headers:{'Accept-Language':'fr-CA,fr;q=0.9'}});if(!r.ok)throw new Error('Impossible de localiser cette ville pour le moment.');const places=await r.json() as Place[];if(!places[0])throw new Error('Ville introuvable. Essaie un nom plus précis.');return{latitude:Number(places[0].lat),longitude:Number(places[0].lon)}};
 const create=async()=>{if(!name.trim()||!city.trim())return;const radiusKm=Number(radius.replace(',','.'));if(!Number.isFinite(radiusKm)||radiusKm<=0){setError('Entre un rayon valide en kilomètres.');return}setSaving(true);setError('');try{const point=await geocode(city.trim());await api('/api/admin/zones',{method:'POST',body:JSON.stringify({name:name.trim(),cityMatch:city.trim(),radiusKm,...point})});setName('');setCity('');setRadius('25');await load()}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setSaving(false)}};
 const updateRate=async(zoneId:string,categoryId:string,value:string)=>{const dollars=Number(value.replace(',','.'));if(!Number.isFinite(dollars)||dollars<=0)return;await api(`/api/admin/zones/${zoneId}/rates/${categoryId}`,{method:'POST',body:JSON.stringify({hourlyRateCents:Math.round(dollars*60*100)})});await load()};
 const useDefault=async(zoneId:string,categoryId:string)=>{await api(`/api/admin/zones/${zoneId}/rates/${categoryId}/default`,{method:'POST',body:'{}'});await load()};
 const saveZone=async(z:Zone,extra:Record<string,unknown>={})=>{await api(`/api/admin/zones/${z.id}`,{method:'POST',body:JSON.stringify({name:z.name,cityMatch:z.city_match,isActive:z.is_active,latitude:z.latitude,longitude:z.longitude,radiusKm:z.radius_km??25,...extra})});await load()};
 const toggle=async(z:Zone)=>saveZone(z,{isActive:!z.is_active});
 const updateRadius=async(z:Zone,value:string)=>{const radiusKm=Number(value.replace(',','.'));if(!Number.isFinite(radiusKm)||radiusKm<=0){setError('Rayon invalide.');return}try{await saveZone(z,{radiusKm})}catch(e){setError(e instanceof Error?e.message:'Erreur')}};
 const locate=async(z:Zone)=>{setLocatingId(z.id);setError('');try{const point=await geocode(z.city_match);await saveZone(z,{...point})}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setLocatingId(null)}};
 const remove=async(z:Zone)=>{if(!confirm(`Supprimer la zone ${z.name}?`))return;await api(`/api/admin/zones/${z.id}/delete`,{method:'POST',body:'{}'});await load()};
 return <>
  <div className="admin-card"><div className="admin-card-top"><div><span className="mission-number">Territoires desservis</span><h3>Zones, rayons et tarifs</h3></div></div><p className="admin-muted">Chaque zone possède un point central et un rayon. Quand le client utilise sa localisation ou valide son adresse, FaisLaJob vérifie automatiquement s’il se trouve dans une zone active. Hors zone, la demande est bloquée.</p><div className="admin-tools"><input placeholder="Nom de la zone (ex. Trois-Rivières)" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Ville centrale" value={city} onChange={e=>setCity(e.target.value)}/><input style={{maxWidth:150}} inputMode="decimal" placeholder="Rayon (km)" value={radius} onChange={e=>setRadius(e.target.value)}/><button disabled={saving||!name.trim()||!city.trim()} onClick={create}>{saving?'Localisation…':'+ Ajouter la zone'}</button></div>{error&&<div className="admin-error">⚠️ {error}</div>}</div>
  {zones.map(z=><div className="admin-card" key={z.id}><div className="admin-card-top"><div><span className="mission-number">Zone #{z.id}</span><h3>{z.name}</h3><small className="admin-muted">Centre : {z.city_match} · Rayon : {Number(z.radius_km??25).toFixed(1).replace('.',',')} km</small>{z.latitude!=null&&z.longitude!=null?<small className="admin-muted">Coordonnées : {Number(z.latitude).toFixed(5)}, {Number(z.longitude).toFixed(5)}</small>:<small className="admin-muted">⚠️ Cette ancienne zone n’a pas encore de coordonnées GPS.</small>}</div><span className={`online-dot ${z.is_active?'on':''}`}>{z.is_active?'● Active':'○ Inactive'}</span></div><div className="admin-tools"><label style={{display:'flex',alignItems:'center',gap:8}}>Rayon <input style={{maxWidth:110}} inputMode="decimal" defaultValue={Number(z.radius_km??25).toFixed(1)} onBlur={e=>updateRadius(z,e.target.value)}/> km</label><button onClick={()=>locate(z)} disabled={locatingId===z.id}>{locatingId===z.id?'Localisation…':'📍 Repositionner sur la ville'}</button></div><div className="admin-table-wrap"><table><thead><tr><th>Catégorie</th><th>Tarif général</th><th>Tarif zone / min</th><th>Équiv. / h</th><th></th></tr></thead><tbody>{z.rates.map(r=>{const active=r.hourly_rate_cents??r.default_hourly_rate_cents;return <tr key={r.category_id}><td><strong>{r.category_name}</strong></td><td>{money(r.default_hourly_rate_cents)}</td><td><input style={{maxWidth:110}} inputMode="decimal" defaultValue={active?((active/100)/60).toFixed(2):''} onBlur={e=>updateRate(z.id,r.category_id,e.target.value)}/></td><td><strong>{money(active)}</strong>{r.hourly_rate_cents!=null&&<small>tarif zone</small>}</td><td>{r.hourly_rate_cents!=null&&<button onClick={()=>useDefault(z.id,r.category_id)}>Tarif général</button>}</td></tr>})}</tbody></table></div><div className="admin-actions"><button onClick={()=>toggle(z)}>{z.is_active?'Désactiver':'Activer'}</button><button className="danger" onClick={()=>remove(z)}>Supprimer la zone</button></div></div>)}
  {zones.length===0&&<div className="admin-empty">Aucune zone configurée. Ajoute par exemple Trois-Rivières avec un rayon de 25 km.</div>}
 </>;
}
