import { useEffect, useState } from 'react';
import './public-home.css';
import './mascot-fix.css';
import mascotData from './mascot-data';

type User={id:string;email:string;role:'client'|'provider';client_id:string|null;provider_id:string|null;name:string;phone?:string|null};
type Props={onAuthenticated:(user:User)=>void};

type ServiceZone={code:string;name:string;lat:number;lng:number;radiusKm:number};
const ZONES:ServiceZone[]=[{code:'M1',name:'Trois-Rivières',lat:46.3430,lng:-72.5430,radiusKm:25}];
const distanceKm=(lat1:number,lng1:number,lat2:number,lng2:number)=>{const r=6371;const dLat=(lat2-lat1)*Math.PI/180;const dLng=(lng2-lng1)*Math.PI/180;const a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLng/2)**2;return 2*r*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))};
const findZone=(lat:number,lng:number)=>ZONES.find(zone=>distanceKm(lat,lng,zone.lat,zone.lng)<=zone.radiusKm)||null;

const services=[['🧹','Ménage'],['🛠️','Petites réparations'],['🌿','Extérieur & terrain'],['🚚','Déménagement'],['🐾','Animaux et plus']] as const;
const BRAND_LOGO='/faislajob-logo-hq.svg?v=20260826-1';
const Logo=({className}:{className:string})=><img src={BRAND_LOGO} alt="FaisLaJob.ca" className={className} draggable={false} style={{height:'auto',width:'min(100%,190px)',maxHeight:'54px',objectFit:'contain',display:'block'}}/>;

export default function AuthScreen({onAuthenticated}:Props){
  const[showForm,setShowForm]=useState(false);const[mode,setMode]=useState<'login'|'register'>('login');const[role,setRole]=useState<'client'|'provider'>('client');const[name,setName]=useState('');const[email,setEmail]=useState('');const[phone,setPhone]=useState('');const[password,setPassword]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[sector,setSector]=useState('Localisation…');
  useEffect(()=>{if(!navigator.geolocation){setSector('Hors secteur');return}navigator.geolocation.getCurrentPosition(({coords})=>{const zone=findZone(coords.latitude,coords.longitude);setSector(zone?`${zone.code}-${zone.name}`:'Hors secteur')},()=>setSector('Hors secteur'),{enableHighAccuracy:true,timeout:8000,maximumAge:300000})},[]);
  const openForm=(next:'login'|'register')=>{setMode(next);setShowForm(true);setError('');window.scrollTo({top:0,behavior:'smooth'})};
  const submit=async()=>{setLoading(true);setError('');try{const endpoint=mode==='login'?'/api/auth/login':'/api/auth/register';const body=mode==='login'?{email,password}:{name,email,phone,password,role};const r=await fetch(endpoint,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Connexion impossible.');onAuthenticated(data.user as User)}catch(e){setError(e instanceof Error?e.message:'Une erreur est survenue.')}finally{setLoading(false)}};
  if(showForm)return <main className="public-home"><section className="auth-panel"><button className="auth-back" onClick={()=>setShowForm(false)}>← Retour</button><div className="auth-logo"><Logo className="auth-logo-image"/></div><div className="role-switch"><button className={role==='client'?'active':''} onClick={()=>setRole('client')}>Client</button><button className={role==='provider'?'active':''} onClick={()=>setRole('provider')}>Partenaire</button></div><div className="auth-kicker">{mode==='login'?'Connexion':'Créer un compte'}</div><h1>{mode==='login'?'Content de te revoir':'Bienvenue chez FaisLaJob'}</h1><p>{role==='client'?'Demande un service en quelques étapes simples.':'Accède directement aux jobs disponibles et à tes missions.'}</p>{mode==='register'&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom complet"/>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Courriel" inputMode="email" autoCapitalize="none"/>{mode==='register'&&<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Téléphone" inputMode="tel"/>}<input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mot de passe" type="password"/>{error&&<div className="auth-error">⚠️ {error}</div>}<button className="home-primary" onClick={submit} disabled={loading||!email.trim()||password.length<8||(mode==='register'&&name.trim().length<2)}>{loading?'Patiente…':mode==='login'?'Se connecter':'Créer mon compte'}</button><button className="home-secondary" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Pas encore de compte? Créer un compte':'J’ai déjà un compte'}</button></section></main>;
  return <main className="fj-home"><section className="fj-hero"><div className="fj-topbar"><Logo className="fj-logo-image"/><div className={`fj-sector ${sector==='Hors secteur'?'out-of-zone':''}`}><span>📍</span><span>Votre secteur<b>{sector}</b></span></div></div><div className="fj-tagline">LE COUP DE MAIN QU’IL TE FAUT,<strong>QUAND TU EN AS BESOIN.</strong></div><div className="fj-hero-body"><div className="fj-benefits"><div><i>⚡</i><span><b>Rapide & simple</b><small>Demande en quelques étapes</small></span></div><div><i>✓</i><span><b>Fiable & sécuritaire</b><small>Prestataires vérifiés</small></span></div><div><i>📍</i><span><b>Service local</b><small>Dans ton secteur</small></span></div></div><div className="fj-mascot-card" aria-hidden="true"><img src={mascotData} alt="" className="fj-mascot-image" draggable={false}/></div></div></section><button className="fj-request" onClick={()=>window.location.href='/request'}><div className="fj-phone">📱</div><span><small>NOUVELLE DEMANDE</small><strong>Dis-nous ce dont<br/>tu as <em>besoin</em></strong><b>On s’occupe du reste.</b></span><i>→</i></button><section className="fj-services"><div className="fj-kicker">DES CENTAINES DE SERVICES</div><h2>On a la personne pour le faire.</h2><div className="fj-service-grid">{services.map(([icon,label])=><button key={label} onClick={()=>window.location.href='/request'}>{icon}<span>{label}</span></button>)}</div></section><div className="fj-trust"><span>🛡️ Prestataires vérifiés</span><span>👥 Assurés</span><span>☆ Évalués par des clients comme toi</span></div><div className="fj-auth-actions"><button className="fj-login" onClick={()=>openForm('login')}>👤 <b>Se connecter</b> ›</button><button className="fj-register" onClick={()=>openForm('register')}>👤＋ <b>Créer un compte</b> ›</button></div><div className="fj-rating"><span>Plus de 1000+ clients satisfaits</span><strong>★★★★★ <b>4,9/5</b></strong></div></main>;
}
