import './client-premium.css';
import c0 from './mascot-chunk-0';import c1 from './mascot-chunk-1';import c2 from './mascot-chunk-2';import c3 from './mascot-chunk-3';import c4 from './mascot-chunk-4';import c5 from './mascot-chunk-5';import c6 from './mascot-chunk-6';import c7 from './mascot-chunk-7';
declare global{interface Window{__fjReveal?:()=>void}}
const mascot=`data:image/webp;base64,${c0}${c1}${c2}${c3}${c4}${c5}${c6}${c7}`;
const promoSeenKey='fj_seen_promotions';
function nav(label:string){return [...document.querySelectorAll<HTMLButtonElement>('.user-portal-nav nav button')].find(b=>(b.textContent||'').includes(label))}function go(label:string){nav(label)?.click();remountSoon()}
function client(){return !!nav('Mes commandes')&&!nav('Jobs')}
function seenPromos(){try{return new Set<string>(JSON.parse(localStorage.getItem(promoSeenKey)||'[]'))}catch{return new Set<string>()}}
function markPromosSeen(ids:string[]){try{localStorage.setItem(promoSeenKey,JSON.stringify([...new Set([...seenPromos(),...ids])]))}catch{}}
function ensureMobilePolishStyles(){if(document.getElementById('fj-mobile-polish'))return;const style=document.createElement('style');style.id='fj-mobile-polish';style.textContent=`
@media(max-width:650px){
  .user-portal-nav{width:100%!important;min-height:58px!important;padding:11px 12px 9px!important;display:flex!important;align-items:center!important;justify-content:center!important;border-bottom:1px solid #193555!important;background:#050e1b!important;box-sizing:border-box!important}
  .user-portal-nav nav,.user-portal-nav .portal-role,.user-portal-nav .portal-user,.user-portal-nav .portal-logout{display:none!important}
  .user-portal-nav .portal-brand{display:block!important;margin:0 auto!important;padding:5px 10px!important;font-size:1.55rem!important;line-height:1!important}
  .client-home-premium{padding-top:8px!important}
  .client-premium-hero{padding:14px 14px 13px!important;margin-bottom:12px!important;border-radius:19px!important}
  .client-hero-top{grid-template-columns:56% 44%!important;min-height:184px!important}
  .client-hero-kicker{font-size:.58rem!important;margin-bottom:9px!important}
  .client-hero-copy h1{font-size:1.62rem!important;line-height:1.01!important}
  .client-hero-copy p{font-size:.72rem!important;line-height:1.38!important;margin-top:10px!important;max-width:175px!important}
  .client-hero-visual{min-height:184px!important}
  .client-hero-visual img{width:154px!important;height:184px!important;right:-18px!important;bottom:-5px!important}
  .client-floating{width:31px!important;height:31px!important;border-radius:10px!important;font-size:.82rem!important}
  .client-check{top:22%!important}.client-user{top:52%!important}.client-star{font-size:1.15rem!important}
  .client-hero-cta{height:50px!important;font-size:.9rem!important;border-radius:12px!important}
  .client-quick-grid{gap:7px!important;margin-top:14px!important}
  .client-quick-grid button{height:98px!important;padding:7px 3px!important;border-radius:13px!important}
  .quick-icon{width:36px!important;height:36px!important;margin-bottom:6px!important;font-size:.9rem!important}
  .client-quick-grid strong{font-size:.57rem!important;line-height:1.08!important;min-height:22px!important}
  .client-quick-grid small{font-size:.53rem!important;line-height:1.1!important;margin-top:2px!important}
  .client-bottom-nav button{color:#8ca2bb!important;transition:color .16s ease,transform .16s ease}
  .client-bottom-nav button.active{color:#42a8ff!important}
  .client-bottom-nav button.active .client-nav-icon{transform:translateY(-1px)}
  .client-bottom-nav .client-bottom-plus{color:#fff!important}
  .client-nav-icon{display:grid;place-items:center;transition:transform .16s ease}
}
`;document.head.appendChild(style)}
function refreshPromoBadge(root:HTMLElement){const button=root.querySelector<HTMLButtonElement>('[data-action="promos"]'),badge=button?.querySelector<HTMLElement>('.client-promo-badge');if(!button||!badge)return;fetch('/api/client/promotions',{credentials:'same-origin',cache:'no-store'}).then(async r=>{if(!r.ok)return;const d=await r.json().catch(()=>({}));const ids=(Array.isArray(d.promotions)?d.promotions:[]).map((p:any)=>String(p?.id||'')).filter(Boolean);button.dataset.promoIds=ids.join(',');const seen=seenPromos();const newCount=ids.filter((id:string)=>!seen.has(id)).length;badge.textContent=newCount>99?'99+':String(newCount);badge.hidden=newCount===0}).catch(()=>{})}
function hero(main:HTMLElement){const existing=main.querySelector<HTMLElement>('.client-premium-hero');if(existing){refreshPromoBadge(existing);return}const stats=main.querySelector('.portal-stats');if(!stats)return;const kicker=main.querySelector('.portal-kicker')?.textContent||'Bonjour 👋';const el=document.createElement('section');el.className='client-premium-hero';el.innerHTML=`<div class="client-hero-top"><div class="client-hero-copy"><span class="client-hero-kicker">${kicker}</span><h1>Prêt à déléguer<br>une tâche ?</h1><p>FaisLaJob s’occupe de trouver le<br class="desktop-break"> bon partenaire pour toi.</p></div><div class="client-hero-visual"><img src="${mascot}" alt="Mascotte FaisLaJob"><span class="client-floating client-check">✓</span><span class="client-floating client-user">○</span><span class="client-star">✦</span></div></div><button class="client-hero-cta" data-action="request"><b>＋</b> Nouvelle demande</button><div class="client-quick-grid"><button data-action="promos" style="position:relative"><span class="client-promo-badge" hidden style="position:absolute;right:10px;top:9px;min-width:21px;height:21px;padding:0 5px;border-radius:999px;background:#ff2d2d;color:#fff;font-size:12px;font-weight:900;line-height:21px;text-align:center;box-sizing:border-box;box-shadow:0 0 0 3px #0d1d31,0 4px 12px rgba(255,45,45,.45);z-index:2">0</span><span class="quick-icon qi-blue">%</span><strong>Offres spéciales</strong><small>Voir les promos</small></button><button data-action="support"><span class="quick-icon qi-green">•••</span><strong>Aide</strong><small>Centre d’aide</small></button><button data-action="request"><span class="quick-icon qi-yellow">◷</span><strong>Demande rapide</strong><small>En 2 minutes</small></button><button data-action="payments"><span class="quick-icon qi-purple">✓</span><strong>Paiement sécurisé</strong><small>100% protégé</small></button></div>`;stats.parentElement?.insertBefore(el,stats);refreshPromoBadge(el);el.onclick=e=>{const target=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');const a=target?.dataset.action;if(a==='request')location.href='/request';if(a==='promos')location.href='/promotions';if(a==='promos'){const ids=(target?.dataset.promoIds||'').split(',').filter(Boolean);markPromosSeen(ids);const badge=target?.querySelector<HTMLElement>('.client-promo-badge');if(badge)badge.hidden=true;location.href='/promotions'}if(a==='payments')go('Paiements');if(a==='support')window.dispatchEvent(new Event('faislajob-open-support'))}}
function refreshMessageBadge(){const button=document.querySelector<HTMLButtonElement>('.client-bottom-nav [data-action="messages"]');if(!button)return;let badge=button.querySelector<HTMLElement>('.client-message-badge');if(!badge){badge=document.createElement('b');badge.className='client-message-badge';button.style.position='relative';Object.assign(badge.style,{position:'absolute',top:'1px',right:'calc(50% - 24px)',minWidth:'18px',height:'18px',padding:'0 4px',borderRadius:'999px',background:'#ff3347',color:'#fff',fontSize:'10px',fontWeight:'950',lineHeight:'18px',textAlign:'center',boxSizing:'border-box',boxShadow:'0 0 0 2px #050e1b,0 3px 8px rgba(255,51,71,.45)',zIndex:'3',pointerEvents:'none'});button.appendChild(badge)}fetch('/api/client/support/unread',{credentials:'same-origin',cache:'no-store'}).then(async r=>{if(!r.ok)return;const d=await r.json().catch(()=>({}));const n=Number(d.unread||0);badge!.textContent=n>99?'99+':String(n);badge!.hidden=n===0}).catch(()=>{})}
const navIcon=(paths:string)=>`<span class="client-nav-icon" aria-hidden="true"><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${paths}</svg></span>`;
function activeActionFromTitle(title?:string){if(title==='Ton tableau de bord')return'home';if(title==='Tes commandes')return'missions';if(title==='Messages')return'messages';if(title==='Support & FAQ')return'support';return''}
function syncBottomActive(title?:string){const active=activeActionFromTitle(title);document.querySelectorAll<HTMLButtonElement>('.client-bottom-nav button[data-action]').forEach(button=>button.classList.toggle('active',Boolean(active)&&button.dataset.action===active))}
function bottom(){if(document.querySelector('.client-bottom-nav'))return;const b=document.createElement('nav');b.className='client-bottom-nav';const home=navIcon('<path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.5V21h14V9.5"/><path d="M9 21v-7h6v7"/>');const orders=navIcon('<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 4.5V3h6v1.5"/><path d="m9 12 2 2 4-4"/><path d="M9 17h6"/>');const plus=navIcon('<path d="M12 5v14"/><path d="M5 12h14"/>');const messages=navIcon('<path d="M21 15a4 4 0 0 1-4 4H8l-5 3 1.5-5A7 7 0 0 1 3 12a7 7 0 0 1 7-7h7a4 4 0 0 1 4 4Z"/><path d="M8 11h8"/><path d="M8 15h5"/>');const support=navIcon('<path d="M4 13a8 8 0 0 1 16 0"/><path d="M4 13v4a2 2 0 0 0 2 2h1v-6H4Z"/><path d="M20 13v4a2 2 0 0 1-2 2h-1v-6h3Z"/><path d="M17 19c0 1.1-.9 2-2 2h-3"/>');b.innerHTML=`<button data-action="home" aria-label="Accueil">${home}<small>Accueil</small></button><button data-action="missions" aria-label="Commandes">${orders}<small>Commandes</small></button><button class="client-bottom-plus" data-action="request" aria-label="Nouvelle demande">${plus}</button><button data-action="messages" aria-label="Messages">${messages}<small>Messages</small></button><button data-action="support" aria-label="Support">${support}<small>Support</small></button>`;b.onclick=e=>{const target=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');const a=target?.dataset.action;if(a&&a!=='request')b.querySelectorAll('button[data-action]').forEach(x=>x.classList.toggle('active',x===target));if(a==='request')location.href='/request';if(a==='home')go('Accueil');if(a==='missions')go('Mes commandes');if(a==='support')window.dispatchEvent(new Event('faislajob-open-support'));if(a==='messages')window.dispatchEvent(new Event('faislajob-open-messages'));remountSoon()};document.body.appendChild(b);refreshMessageBadge();window.setInterval(refreshMessageBadge,5000)}
function mount(){if(!client())return;ensureMobilePolishStyles();const main=document.querySelector<HTMLElement>('.user-portal-main'),title=main?.querySelector('.portal-top h1')?.textContent?.trim();if(!main)return;main.classList.add('client-premium-shell');bottom();syncBottomActive(title);if(title==='Ton tableau de bord'){main.classList.add('client-home-premium');main.querySelectorAll('.portal-stat').forEach((x,i)=>x.classList.add(`client-stat-${i}`));hero(main)}else{main.classList.remove('client-home-premium');main.querySelector('.client-premium-hero')?.remove()}requestAnimationFrame(()=>window.__fjReveal?.())}
function remountSoon(){[0,20,60,120,220].forEach(ms=>window.setTimeout(mount,ms))}
let q=false;const schedule=()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;mount()})};function start(){ensureMobilePolishStyles();mount();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,characterData:true});document.addEventListener('click',e=>{const target=(e.target as HTMLElement).closest('.user-portal-nav nav button,.client-bottom-nav button');if(target)remountSoon()},true);window.addEventListener('popstate',remountSoon);let n=0,t=setInterval(()=>{mount();if(++n>20)clearInterval(t)},500)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
export {};
