import './client-premium.css';
import c0 from './mascot-chunk-0';import c1 from './mascot-chunk-1';import c2 from './mascot-chunk-2';import c3 from './mascot-chunk-3';import c4 from './mascot-chunk-4';import c5 from './mascot-chunk-5';import c6 from './mascot-chunk-6';import c7 from './mascot-chunk-7';
declare global{interface Window{__fjReveal?:()=>void}}
const mascot=`data:image/webp;base64,${c0}${c1}${c2}${c3}${c4}${c5}${c6}${c7}`;
const promoSeenKey='fj_seen_promotions';
function nav(label:string){return [...document.querySelectorAll<HTMLButtonElement>('.user-portal-nav nav button')].find(b=>(b.textContent||'').includes(label))}function go(label:string){nav(label)?.click()}
function client(){return !!nav('Mes commandes')&&!nav('Jobs')}
function seenPromos(){try{return new Set<string>(JSON.parse(localStorage.getItem(promoSeenKey)||'[]'))}catch{return new Set<string>()}}
function markPromosSeen(ids:string[]){try{localStorage.setItem(promoSeenKey,JSON.stringify([...new Set([...seenPromos(),...ids])]))}catch{}}
function refreshPromoBadge(root:HTMLElement){const button=root.querySelector<HTMLButtonElement>('[data-action="promos"]'),badge=button?.querySelector<HTMLElement>('.client-promo-badge');if(!button||!badge)return;fetch('/api/client/promotions',{credentials:'same-origin',cache:'no-store'}).then(async r=>{if(!r.ok)return;const d=await r.json().catch(()=>({}));const ids=(Array.isArray(d.promotions)?d.promotions:[]).map((p:any)=>String(p?.id||'')).filter(Boolean);button.dataset.promoIds=ids.join(',');const seen=seenPromos();const hasNew=ids.some((id:string)=>!seen.has(id));badge.hidden=!hasNew}).catch(()=>{})}
function hero(main:HTMLElement){if(main.querySelector('.client-premium-hero'))return;const stats=main.querySelector('.portal-stats');if(!stats)return;const kicker=main.querySelector('.portal-kicker')?.textContent||'Bonjour 👋';const el=document.createElement('section');el.className='client-premium-hero';el.innerHTML=`<div class="client-hero-top"><div class="client-hero-copy"><span class="client-hero-kicker">${kicker}</span><h1>Prêt à déléguer<br>une tâche ?</h1><p>FaisLaJob s’occupe de trouver le<br class="desktop-break"> bon partenaire pour toi.</p></div><div class="client-hero-visual"><img src="${mascot}" alt="Mascotte FaisLaJob"><span class="client-floating client-check">✓</span><span class="client-floating client-user">○</span><span class="client-star">✦</span></div></div><button class="client-hero-cta" data-action="request"><b>＋</b> Nouvelle demande</button><div class="client-quick-grid"><button data-action="promos" style="position:relative"><span class="client-promo-badge" hidden style="position:absolute;right:10px;top:9px;width:21px;height:21px;border-radius:999px;background:#ff2d2d;color:#fff;font-size:12px;font-weight:900;line-height:21px;text-align:center;box-shadow:0 0 0 3px #0d1d31,0 4px 12px rgba(255,45,45,.45);z-index:2">1</span><span class="quick-icon qi-blue">%</span><strong>Offres spéciales</strong><small>Voir les promos</small></button><button data-action="support"><span class="quick-icon qi-green">•••</span><strong>Besoin d’aide ?</strong><small>Parle-nous</small></button><button data-action="request"><span class="quick-icon qi-yellow">◷</span><strong>Demande rapide</strong><small>En 2 minutes</small></button><button data-action="payments"><span class="quick-icon qi-purple">✓</span><strong>Paiement sécurisé</strong><small>100% protégé</small></button></div>`;stats.parentElement?.insertBefore(el,stats);refreshPromoBadge(el);el.onclick=e=>{const target=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');const a=target?.dataset.action;if(a==='request')location.href='/request';if(a==='promos'){const ids=(target?.dataset.promoIds||'').split(',').filter(Boolean);markPromosSeen(ids);const badge=target?.querySelector<HTMLElement>('.client-promo-badge');if(badge)badge.hidden=true;location.href='/promotions'}if(a==='payments')go('Paiements');if(a==='support')go('Profil')}}
function bottom(){if(document.querySelector('.client-bottom-nav'))return;const b=document.createElement('nav');b.className='client-bottom-nav';b.innerHTML=`<button data-action="home"><span>⌂</span><small>Accueil</small></button><button data-action="missions"><span>☷</span><small>Commandes</small></button><button class="client-bottom-plus" data-action="request"><span>＋</span></button><button data-action="messages"><span>◌</span><small>Messages</small></button><button data-action="support"><span>♧</span><small>Support</small></button>`;b.onclick=e=>{const a=(e.target as HTMLElement).closest<HTMLElement>('[data-action]')?.dataset.action;if(a==='request')location.href='/request';if(a==='home')go('Accueil');if(a==='missions')go('Mes commandes');if(a==='support'||a==='messages')go('Profil')};document.body.appendChild(b)}
function mount(){if(!client())return;const main=document.querySelector<HTMLElement>('.user-portal-main'),title=main?.querySelector('.portal-top h1')?.textContent?.trim();if(!main)return;main.classList.add('client-premium-shell');bottom();if(title==='Ton tableau de bord'){main.classList.add('client-home-premium');main.querySelectorAll('.portal-stat').forEach((x,i)=>x.classList.add(`client-stat-${i}`));hero(main)}else{main.classList.remove('client-home-premium');main.querySelector('.client-premium-hero')?.remove()}requestAnimationFrame(()=>window.__fjReveal?.())}
let q=false;const schedule=()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;mount()})};function start(){mount();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,characterData:true});let n=0,t=setInterval(()=>{mount();if(++n>20)clearInterval(t)},500)}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
export {};
