import {useEffect,useRef,useState} from 'react';
import './support-messages.css';

type Message={id:string;sender_type:'client'|'admin';body:string;created_at:string;read_at?:string|null};

export default function ClientMessages(){
 const[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState('');
 const endRef=useRef<HTMLDivElement|null>(null);
 const load=async(background=false)=>{if(!background)setLoading(true);try{const r=await fetch('/api/client/support/messages',{credentials:'same-origin',cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Impossible de charger les messages.');setMessages(d.messages||[]);if(!background)setError('')}catch(e){if(!background)setError(e instanceof Error?e.message:'Erreur de messagerie')}finally{if(!background)setLoading(false)}};
 useEffect(()=>{load();const t=window.setInterval(()=>load(true),3000);return()=>window.clearInterval(t)},[]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length]);
 const send=async()=>{const body=text.trim();if(!body||sending)return;setSending(true);setError('');try{const r=await fetch('/api/client/support/messages',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({body})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Envoi impossible.');setText('');await load(true)}catch(e){setError(e instanceof Error?e.message:'Envoi impossible')}finally{setSending(false)}};
 return <section className="support-chat-shell"><div className="support-chat-head"><div className="support-mail-icon">✉️</div><div><span>Boîte de réception</span><h2>Service client FaisLaJob</h2><p>Écris-nous ici. Les réponses de l’équipe apparaîtront dans cette conversation.</p></div><div className="support-online">● Service client</div></div>{error&&<div className="support-chat-error">⚠️ {error}</div>}<div className="support-chat-body">{loading&&messages.length===0?<div className="support-chat-empty">Chargement…</div>:messages.length===0?<div className="support-chat-empty"><div>📬</div><h3>Aucun message pour le moment</h3><p>Écris ton premier message au service client ci-dessous.</p></div>:messages.map(m=><div key={m.id} className={`support-bubble-row ${m.sender_type==='client'?'mine':'theirs'}`}><div className="support-bubble"><small>{m.sender_type==='client'?'Toi':'FaisLaJob'}</small><p>{m.body}</p><time>{new Date(m.created_at).toLocaleString('fr-CA',{dateStyle:'short',timeStyle:'short'})}</time></div></div>)}<div ref={endRef}/></div><div className="support-compose"><textarea rows={2} value={text} maxLength={4000} placeholder="Écris ton message au service client…" onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button disabled={!text.trim()||sending} onClick={send}>{sending?'Envoi…':'Envoyer ➤'}</button></div><div className="support-compose-note">Appuie sur Entrée pour envoyer • Maj + Entrée pour une nouvelle ligne</div></section>
}
