import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import AdminPortal from './AdminPortal';
import UserPortal from './UserPortal';
import './styles.css';
import './portal.css';

const BRAND_LOGO='https://335a351f-416d-4e29-89d5-2204a8876ab2.sandbox.floot.app/_cdn/static/40f11d09-fbf4-43b4-8bbf-9da5343620ff-IMG_2043.png';

type ClientMission = { id: string; status: string; category_name?: string; category_id?: string; provider_id?: string|null; description?:string; created_at?:string; started_at?:string|null; duration_minutes?:number|null };
type ProviderMini = { id:string; name:string; status?:string };
type CategoryRate = { id:string; name:string; hourly_rate_cents?:number|null };
type User={id:string;email:string;role:'client'|'provider';client_id:string|null;provider_id:string|null;name:string;phone?:string|null};
const statusText: Record<string, [string, string, string]> = {
  requested: ['🔎', 'En attente d’un partenaire', 'On cherche un partenaire disponible pour ta job.'],
  offered: ['📣', 'En attente d’un partenaire', 'Ta demande est envoyée aux partenaires disponibles.'],
  assigned: ['🤝', 'Partenaire trouvé', 'Un partenaire a accepté ta mission.'],
  en_route: ['🚗', 'Votre partenaire est en route', 'Il se dirige maintenant vers l’adresse de la job.'],
  arrived: ['📍', 'Votre partenaire est arrivé', 'Il est maintenant sur place.'],
  in_progress: ['🛠️', 'Job en cours', 'Le travail a commencé.'],
  completed: ['✅', 'La job est terminée', 'La facture est prête dans Mes missions.'],
};
const money=(v?:number|null)=>typeof v==='number'?`${(v/100).toFixed(2).replace('.',',')} $`:'—';
function getMissionIdShownOnScreen(){const box=document.querySelector<HTMLElement>('.flow-card .success-box');return box?.textContent?.match(/Mission\s+#(\d+)/i)?.[1]||null;}
function normalizedMissionStatus(mission:ClientMission){return mission.provider_id&&['requested','offered'].includes(mission.status)?'assigned':mission.status;}
function updateVisibleClientScreen(mission:ClientMission){const effectiveStatus=normalizedMissionStatus(mission),status=statusText[effectiveStatus]||['ℹ️','Mise à jour',`Statut : ${effectiveStatus}`],visibleId=getMissionIdShownOnScreen();if(visibleId&&String(visibleId)!==String(mission.id))return;const title=document.querySelector<HTMLElement>('.flow-card .flow-title'),box=document.querySelector<HTMLElement>('.flow-card .success-box');if(title&&box){const nextTitle=`${status[0]} ${status[1]}`,nextBox=`Mission #${mission.id} • ${status[2]}`;if(title.textContent!==nextTitle)title.textContent=nextTitle;if(box.textContent!==nextBox)box.textContent=nextBox;}}
function ClientMissionTracker(){const[mission,setMission]=useState<ClientMission|null>(null);useEffect(()=>{let cancelled=false;const refresh=async()=>{const visibleId=getMissionIdShownOnScreen();if(!visibleId){if(!cancelled)setMission(null);return}try{const r=await fetch(`/api/missions/${visibleId}`,{credentials:'same-origin',cache:'no-store'});if(!r.ok)return;const data=await r.json();const current=(data.mission||data) as ClientMission;if(!cancelled){setMission(current);updateVisibleClientScreen(current)}}catch{}};refresh();const timer=window.setInterval(refresh,3000);return()=>{cancelled=true;window.clearInterval(timer)}},[]);useEffect(()=>{if(!mission)return;const apply=()=>updateVisibleClientScreen(mission);apply();const observer=new MutationObserver(apply);observer.observe(document.body,{childList:true,subtree:true,characterData:true});return()=>observer.disconnect()},[mission?.id,mission?.status,mission?.provider_id]);if(!mission||!getMissionIdShownOnScreen())return null;const effectiveStatus=normalizedMissionStatus(mission),[icon,title,detail]=statusText[effectiveStatus]||['ℹ️',effectiveStatus,'Le statut vient d’être mis à jour.'];return <aside className="client-live-tracker"><div><div className="client-live-eyebrow">Mission #{mission.id}{mission.category_name?` • ${mission.category_name}`:''}</div><strong>{icon} {title}</strong><span>{detail}</span></div></aside>}

function ClientActiveMissionBanner(){
  const[mission,setMission]=useState<ClientMission|null>(null);const[provider,setProvider]=useState<ProviderMini|null>(null);const[hourlyRate,setHourlyRate]=useState<number>(4000);const[open,setOpen]=useState(false);const[now,setNow]=useState(Date.now());
  useEffect(()=>{const tick=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(tick)},[]);
  useEffect(()=>{let stopped=false;const refresh=async()=>{try{const r=await fetch('/api/client/missions',{credentials:'same-origin',cache:'no-store'});if(!r.ok)return;const d=await r.json();const active=(d.missions||[]).find((m:ClientMission)=>!['completed','cancelled'].includes(m.status))||null;if(!active){if(!stopped){setMission(null);setProvider(null)}return}let full=active;try{const mr=await fetch(`/api/missions/${active.id}`,{credentials:'same-origin',cache:'no-store'});if(mr.ok){const md=await mr.json();full=md.mission||md}}catch{}if(!stopped)setMission(full);if(full.provider_id){try{const pr=await fetch(`/api/providers/${full.provider_id}`,{credentials:'same-origin',cache:'no-store'});if(pr.ok){const pd=await pr.json();if(!stopped)setProvider(pd.provider||pd)}}catch{}}else if(!stopped)setProvider(null);try{const cr=await fetch('/api/categories',{credentials:'same-origin',cache:'no-store'});if(cr.ok){const cd=await cr.json();const cats=(cd.categories||[]) as CategoryRate[];const cat=cats.find(c=>String(c.id)===String(full.category_id))||cats.find(c=>c.name===full.category_name);if(cat?.hourly_rate_cents!=null&&!stopped)setHourlyRate(Number(cat.hourly_rate_cents))}}catch{}}catch{}};refresh();const t=window.setInterval(refresh,3000);return()=>{stopped=true;window.clearInterval(t)}},[]);
  if(!mission)return null;
  const effective=normalizedMissionStatus(mission);const [icon,title,detail]=statusText[effective]||['📋',effective,'Mise à jour de ta mission.'];
  const started=mission.started_at?new Date(mission.started_at).getTime():null;const elapsed=started?Math.max(0,Math.floor((now-started)/1000)):0;const hh=String(Math.floor(elapsed/3600)).padStart(2,'0'),mm=String(Math.floor((elapsed%3600)/60)).padStart(2,'0'),ss=String(elapsed%60).padStart(2,'0');
  const actualMinutes=Math.max(1,Math.ceil(elapsed/60));const billableMinutes=Math.max(15,actualMinutes);const subtotal=Math.ceil(hourlyRate*billableMinutes/60);const serviceFee=Math.ceil(subtotal*.11);const estimatedTotal=subtotal+serviceFee;
  const inProgress=effective==='in_progress';
  return <div style={{position:'relative',zIndex:20,background:'#07101f',padding:'14px 18px 0'}}><div style={{width:'100%',maxWidth:1100,margin:'0 auto',background:inProgress?'linear-gradient(135deg,#063f2e,#082f25)':'linear-gradient(135deg,#12315a,#0d203b)',border:`2px solid ${inProgress?'#1fc77a':'#2693ff'}`,borderRadius:24,padding:'20px',color:'#fff',boxShadow:'0 12px 34px rgba(0,0,0,.35)'}}>
    <button onClick={()=>setOpen(v=>!v)} style={{all:'unset',width:'100%',display:'block',cursor:'pointer'}}>
      <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><span style={{display:'inline-flex',alignItems:'center',gap:8,padding:'7px 13px',borderRadius:999,background:inProgress?'rgba(31,199,122,.18)':'rgba(38,147,255,.16)',color:inProgress?'#8bf0be':'#9dcfff',fontWeight:900,textTransform:'uppercase',letterSpacing:1}}>Mission active</span><span style={{color:'#d7e2ef'}}>Mission #{mission.id}</span></div>
      <div style={{marginTop:20}}><strong style={{display:'block',fontSize:'clamp(28px,6vw,42px)'}}>{icon} {title}</strong><span style={{display:'block',color:'#d5dfeb',marginTop:5,fontSize:17}}>{detail}</span></div>
      {provider&&<div style={{display:'flex',alignItems:'center',gap:12,marginTop:22}}><div style={{width:54,height:54,borderRadius:'50%',display:'grid',placeItems:'center',background:'rgba(255,255,255,.12)',fontSize:22,fontWeight:900}}>{provider.name?.[0]?.toUpperCase()||'P'}</div><div><strong style={{display:'block',fontSize:20}}>{provider.name}</strong><span style={{color:'#b9c9d7'}}>Partenaire</span></div></div>}
      {inProgress&&<><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:18,marginTop:22,paddingTop:18,borderTop:'1px solid rgba(255,255,255,.14)'}}><div><small style={{display:'block',color:'#7ee2b0',fontWeight:900,textTransform:'uppercase'}}>Temps écoulé</small><strong style={{display:'block',fontSize:'clamp(30px,8vw,46px)',marginTop:5,color:'#37e18d'}}>{hh}:{mm}:{ss}</strong><span style={{color:'#b9c9d7'}}>Facturation en cours</span></div><div style={{textAlign:'right'}}><small style={{display:'block',color:'#7ee2b0',fontWeight:900,textTransform:'uppercase'}}>Estimé total</small><strong style={{display:'block',fontSize:'clamp(30px,8vw,46px)',marginTop:5}}>{money(estimatedTotal)}</strong><span style={{color:'#b9c9d7'}}>Basé sur {money(hourlyRate)}/h</span></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:18,marginTop:18,paddingTop:18,borderTop:'1px solid rgba(255,255,255,.14)'}}><div><small style={{display:'block',color:'#7ee2b0',fontWeight:900,textTransform:'uppercase'}}>Facturation</small><strong style={{display:'block',fontSize:'clamp(28px,7vw,40px)',marginTop:4}}>{money(subtotal)}</strong><span style={{color:'#b9c9d7'}}>{billableMinutes} min facturées</span></div><div style={{textAlign:'right'}}><small style={{display:'block',color:'#7ee2b0',fontWeight:900,textTransform:'uppercase'}}>Frais de service</small><strong style={{display:'block',fontSize:'clamp(28px,7vw,40px)',marginTop:4}}>{money(serviceFee)}</strong><span style={{color:'#b9c9d7'}}>Estimation en direct</span></div></div></>}
      <div style={{marginTop:20,padding:'15px 16px',borderRadius:16,border:'1px solid rgba(255,255,255,.13)',display:'flex',alignItems:'center',gap:12,background:'rgba(0,0,0,.13)'}}><span style={{fontSize:24}}>☷</span><strong style={{flex:1,fontSize:17}}>Voir les détails de la mission</strong><span style={{fontSize:24}}>{open?'⌃':'›'}</span></div>
    </button>
    {open&&<div style={{marginTop:12,background:'rgba(0,0,0,.18)',border:'1px solid rgba(255,255,255,.12)',borderRadius:16,padding:'16px 18px',color:'#eaf2ff'}}><strong>{mission.category_name||'Mission'} • #{mission.id}</strong>{mission.description&&<p style={{whiteSpace:'pre-line',lineHeight:1.55,color:'#b8c8dc',marginBottom:0}}>{mission.description}</p>}{inProgress&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:14}}><span style={{color:'#b8c8dc'}}>Temps facturé</span><strong style={{textAlign:'right'}}>{billableMinutes} min</strong><span style={{color:'#b8c8dc'}}>Sous-total</span><strong style={{textAlign:'right'}}>{money(subtotal)}</strong><span style={{color:'#b8c8dc'}}>Frais de service estimés</span><strong style={{textAlign:'right'}}>{money(serviceFee)}</strong><span style={{color:'#b8c8dc'}}>Total estimé</span><strong style={{textAlign:'right'}}>{money(estimatedTotal)}</strong></div>}</div>}
  </div></div>;
}

function LogoInjector(){useEffect(()=>{const apply=()=>{document.querySelectorAll<HTMLElement>('.brand-button').forEach(el=>{if(el.dataset.logoApplied==='1')return;el.dataset.logoApplied='1';el.textContent='';const img=document.createElement('img');img.src=BRAND_LOGO;img.alt='FaisLaJob.ca';img.style.height='52px';img.style.width='auto';img.style.maxWidth='190px';img.style.objectFit='contain';img.style.display='block';el.appendChild(img);});document.querySelectorAll<HTMLElement>('.admin-logo').forEach(el=>{if(el.dataset.logoApplied==='1')return;el.dataset.logoApplied='1';const hasAdmin=/admin/i.test(el.textContent||'');el.textContent='';el.style.display='flex';el.style.alignItems='center';el.style.gap='9px';const img=document.createElement('img');img.src=BRAND_LOGO;img.alt='FaisLaJob.ca';img.style.height='46px';img.style.width='auto';img.style.maxWidth='175px';img.style.objectFit='contain';img.style.display='block';el.appendChild(img);if(hasAdmin){const badge=document.createElement('span');badge.textContent='Admin';badge.style.fontSize='.72rem';badge.style.fontWeight='900';badge.style.padding='4px 7px';badge.style.borderRadius='999px';badge.style.background='#1577E6';badge.style.color='white';el.appendChild(badge);}});};apply();const observer=new MutationObserver(apply);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect();},[]);return null;}
function RoleGuardMessage({user}:{user:User}){return <main className="page-shell"><section className="flow-card" style={{marginTop:30}}><div className="eyebrow">Compte {user.role==='provider'?'partenaire':'client'}</div><h1 className="flow-title">Cette page n’est pas disponible pour ce compte</h1><p className="flow-copy">Tu es connecté comme {user.role==='provider'?'partenaire':'client'}. FaisLaJob garde maintenant les deux portails séparés pour éviter de mélanger les sessions.</p><button className="primary-button full-button" onClick={()=>{window.location.href='/'}}>Retour à mon portail</button></section></main>}
function RootRouter(){const [user,setUser]=useState<User|null|undefined>(undefined);const path=window.location.pathname;const loadUser=async()=>{try{const r=await fetch('/api/auth/me',{credentials:'same-origin',cache:'no-store'});if(!r.ok){setUser(null);return}setUser((await r.json()).user)}catch{setUser(null)}};useEffect(()=>{loadUser()},[]);useEffect(()=>{if(user!==null)return;let stopped=false;const check=async()=>{if(stopped)return;try{const r=await fetch('/api/auth/me',{credentials:'same-origin',cache:'no-store'});if(r.ok){const next=(await r.json()).user as User;if(!stopped)setUser(next)}}catch{}};const timer=window.setInterval(check,800);return()=>{stopped=true;window.clearInterval(timer)}},[user]);const logout=async()=>{await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'});localStorage.clear();setUser(null);window.location.href='/'};if(user===undefined)return <main className="page-shell"><section className="flow-card" style={{marginTop:30}}><p className="flow-copy">Chargement de FaisLaJob…</p></section></main>;const isRequest=path==='/request'||path.startsWith('/request/');if(isRequest){if(user?.role==='provider')return <RoleGuardMessage user={user}/>;return <><App/><ClientMissionTracker/></>}if(user)return <>{user.role==='client'&&<ClientActiveMissionBanner/>}<UserPortal user={user} onLogout={logout}/></>;return <><App/><ClientMissionTracker/></>}
const isAdmin=window.location.pathname==='/admin'||window.location.pathname.startsWith('/admin/');
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><LogoInjector/>{isAdmin?<AdminPortal/>:<RootRouter/>}</React.StrictMode>);
