import { useEffect, useMemo, useState } from 'react';
import './promotions-admin.css';

type Promotion={id:string;name:string;description?:string|null;kind:'fixed'|'percent';value:number;trigger_type:'always'|'after_orders'|'first_orders';trigger_count:number;min_order_cents:number;starts_at?:string|null;ends_at?:string|null;active:boolean;max_uses_per_client?:number|null;total_uses?:number};
type FormState={name:string;description:string;kind:'fixed'|'percent';value:string;triggerType:'always'|'after_orders'|'first_orders';triggerCount:string;minOrder:string;startsAt:string;endsAt:string;maxUses:string};

const emptyForm:FormState={name:'',description:'',kind:'fixed',value:'5',triggerType:'always',triggerCount:'3',minOrder:'0',startsAt:'',endsAt:'',maxUses:''};
const money=(cents:number)=>`${(cents/100).toFixed(2).replace('.',',')} $`;
const promoValue=(p:Promotion)=>p.kind==='percent'?`${(p.value/100).toFixed(p.value%100===0?0:2).replace('.',',')} %`:money(p.value);

export default function PromotionsAdmin({token}:{token:string}){
 const[promotions,setPromotions]=useState<Promotion[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[editing,setEditing]=useState<Promotion|null>(null);const[form,setForm]=useState<FormState>(emptyForm);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);
 const headers=useMemo(()=>({'x-admin-token':token,'Content-Type':'application/json'}),[token]);
 const api=async(path:string,options:RequestInit={})=>{const r=await fetch(path,{...options,headers:{...headers,...(options.headers as Record<string,string>||{})},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Erreur ${r.status}`);return d};
 const load=async()=>{setLoading(true);setError('');try{const d=await api('/api/admin/promotions');setPromotions(d.promotions||[])}catch(e){setError(e instanceof Error?e.message:'Impossible de charger les promotions')}finally{setLoading(false)}};
 useEffect(()=>{load()},[token]);
 const set=(key:keyof FormState,value:string)=>setForm(f=>({...f,[key]:value}));
 const newPromo=()=>{setEditing(null);setForm(emptyForm);setOpen(true);setError('')};
 const editPromo=(p:Promotion)=>{setEditing(p);setForm({name:p.name,description:p.description||'',kind:p.kind,value:String(p.value/100).replace('.',','),triggerType:p.trigger_type,triggerCount:String(p.trigger_count||3),minOrder:String((p.min_order_cents||0)/100).replace('.',','),startsAt:p.starts_at?p.starts_at.slice(0,10):'',endsAt:p.ends_at?p.ends_at.slice(0,10):'',maxUses:p.max_uses_per_client?String(p.max_uses_per_client):''});setOpen(true);setError('')};
 const numeric=(v:string)=>Number(v.replace(',','.'));
 const save=async()=>{const value=numeric(form.value),minOrder=numeric(form.minOrder||'0'),triggerCount=Math.max(0,Math.round(Number(form.triggerCount||0))),maxUses=form.maxUses?Math.max(1,Math.round(Number(form.maxUses))):null;if(!form.name.trim()){setError('Entre un nom pour la promotion.');return}if(!Number.isFinite(value)||value<=0){setError('Entre une valeur de rabais valide.');return}if(form.kind==='percent'&&value>100){setError('Le pourcentage ne peut pas dépasser 100 %.');return}if(!Number.isFinite(minOrder)||minOrder<0){setError('Le montant minimum est invalide.');return}setSaving(true);setError('');try{const body={name:form.name.trim(),description:form.description.trim(),kind:form.kind,value:Math.round(value*100),triggerType:form.triggerType,triggerCount:form.triggerType==='always'?0:triggerCount,minOrderCents:Math.round(minOrder*100),startsAt:form.startsAt||null,endsAt:form.endsAt||null,maxUsesPerClient:maxUses};await api(editing?`/api/admin/promotions/${editing.id}`:'/api/admin/promotions',{method:'POST',body:JSON.stringify(body)});setOpen(false);setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible')}finally{setSaving(false)}};
 const toggle=async(p:Promotion)=>{try{await api(`/api/admin/promotions/${p.id}/toggle`,{method:'POST',body:JSON.stringify({active:!p.active})});await load()}catch(e){setError(e instanceof Error?e.message:'Action impossible')}};
 const remove=async(p:Promotion)=>{if(!window.confirm(`Supprimer la promotion « ${p.name} »?`))return;try{await api(`/api/admin/promotions/${p.id}/delete`,{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'Suppression impossible')}};
 const preview=()=>{const amount=numeric(form.value);const discount=form.kind==='percent'?`${Number.isFinite(amount)?amount:0} %`:`${Number.isFinite(amount)?amount.toFixed(2).replace('.',','):'0,00'} $`;const trigger=form.triggerType==='after_orders'?`après ${form.triggerCount||0} commandes`:form.triggerType==='first_orders'?`sur les ${form.triggerCount||0} premières commandes`:'sur toutes les commandes admissibles';return `${discount} ${trigger}`};
 return <div className="promo-admin">
  <section className="promo-admin-hero"><div><span className="mission-number">Moteur de promotions</span><h2>Promotions et ristournes</h2><p>Crée des offres sans code compliqué. Les clients voient automatiquement les promotions auxquelles ils ont droit.</p></div><button className="promo-new" onClick={newPromo}>＋ Créer une promotion</button></section>
  {error&&<div className="admin-error">⚠️ {error}</div>}
  <section className="promo-help-grid"><div><b>💵 Rabais fixe</b><span>Ex. 5 $ de rabais</span></div><div><b>％ Pourcentage</b><span>Ex. 10 % de rabais</span></div><div><b>🎯 Fidélité</b><span>Ex. après 3 commandes</span></div><div><b>📅 Planifiée</b><span>Début et fin automatiques</span></div></section>
  <section className="promo-list-card"><div className="promo-list-head"><div><h3>Promotions créées</h3><span>{promotions.length} promotion{promotions.length!==1?'s':''}</span></div><button className="admin-refresh" onClick={load}>↻ Actualiser</button></div>{loading?<div className="admin-empty">Chargement…</div>:promotions.length===0?<div className="promo-empty"><div>🎁</div><h3>Aucune promotion pour le moment</h3><p>Crée ta première offre avec le bouton ci-dessus.</p></div>:<div className="promo-cards">{promotions.map(p=><article className={`promo-admin-card ${p.active?'is-active':''}`} key={p.id}><div className="promo-admin-card-top"><div><span className="promo-state">{p.active?'● Active':'○ Inactive'}</span><h3>{p.name}</h3><p>{p.description||'Aucune description'}</p></div><strong className="promo-big-value">{promoValue(p)}</strong></div><div className="promo-rule-grid"><div><small>Quand?</small><b>{p.trigger_type==='after_orders'?`Après ${p.trigger_count} commandes`:p.trigger_type==='first_orders'?`${p.trigger_count} premières commandes`:'Toujours'}</b></div><div><small>Commande minimum</small><b>{p.min_order_cents?money(p.min_order_cents):'Aucun'}</b></div><div><small>Période</small><b>{p.starts_at?new Date(p.starts_at).toLocaleDateString('fr-CA'):'Maintenant'} → {p.ends_at?new Date(p.ends_at).toLocaleDateString('fr-CA'):'Sans fin'}</b></div><div><small>Limite/client</small><b>{p.max_uses_per_client??'Illimitée'}</b></div></div><div className="promo-card-footer"><span>{p.total_uses||0} utilisation{(p.total_uses||0)!==1?'s':''}</span><div><button onClick={()=>editPromo(p)}>✏️ Modifier</button><button onClick={()=>toggle(p)}>{p.active?'⏸ Désactiver':'▶ Activer'}</button><button className="danger" onClick={()=>remove(p)}>Supprimer</button></div></div></article>)}</div>}</section>
  {open&&<div className="promo-modal-bg" onClick={()=>setOpen(false)}><div className="promo-modal" onClick={e=>e.stopPropagation()}><div className="promo-modal-head"><div><span className="mission-number">{editing?'Modifier':'Nouvelle'} promotion</span><h2>{editing?'Modifier l’offre':'Créer une promotion'}</h2></div><button onClick={()=>setOpen(false)}>✕</button></div><div className="promo-form">
   <section><div className="promo-step"><span>1</span><div><b>Nom et message</b><small>Ce que le client va voir.</small></div></div><label>Nom de la promotion<input value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Ex. Merci pour ta fidélité"/></label><label>Description<textarea value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Ex. Après 3 commandes, profite de 5 $ de rabais sur ta prochaine job." rows={3}/></label></section>
   <section><div className="promo-step"><span>2</span><div><b>Quel rabais?</b><small>Choisis le type et la valeur.</small></div></div><div className="promo-choice-row"><button className={form.kind==='fixed'?'selected':''} onClick={()=>set('kind','fixed')}>💵 Montant fixe</button><button className={form.kind==='percent'?'selected':''} onClick={()=>set('kind','percent')}>％ Pourcentage</button></div><label>{form.kind==='fixed'?'Rabais en dollars':'Rabais en pourcentage'}<div className="promo-value-input"><input inputMode="decimal" value={form.value} onChange={e=>set('value',e.target.value)}/><span>{form.kind==='fixed'?'$':'%'}</span></div></label></section>
   <section><div className="promo-step"><span>3</span><div><b>Quand s’applique-t-elle?</b><small>Choisis une règle simple.</small></div></div><div className="promo-trigger-grid"><button className={form.triggerType==='always'?'selected':''} onClick={()=>set('triggerType','always')}><b>Toujours</b><small>Pour tous les clients admissibles</small></button><button className={form.triggerType==='after_orders'?'selected':''} onClick={()=>set('triggerType','after_orders')}><b>Après X commandes</b><small>Récompense de fidélité</small></button><button className={form.triggerType==='first_orders'?'selected':''} onClick={()=>set('triggerType','first_orders')}><b>Premières commandes</b><small>Promotion de bienvenue</small></button></div>{form.triggerType!=='always'&&<label>Nombre de commandes<input type="number" min="1" value={form.triggerCount} onChange={e=>set('triggerCount',e.target.value)}/><small>{form.triggerType==='after_orders'?`Le client débloque l’offre après ${form.triggerCount||0} commandes terminées.`:`Valide pendant les ${form.triggerCount||0} premières commandes.`}</small></label>}</section>
   <section><div className="promo-step"><span>4</span><div><b>Conditions</b><small>Facultatif.</small></div></div><div className="promo-two"><label>Commande minimum ($)<input inputMode="decimal" value={form.minOrder} onChange={e=>set('minOrder',e.target.value)}/><small>0 = aucun minimum</small></label><label>Maximum par client<input type="number" min="1" value={form.maxUses} onChange={e=>set('maxUses',e.target.value)} placeholder="Illimité"/><small>Vide = illimité</small></label></div></section>
   <section><div className="promo-step"><span>5</span><div><b>Planification</b><small>Laisse vide pour commencer maintenant et ne jamais finir.</small></div></div><div className="promo-two"><label>Date de début<input type="date" value={form.startsAt} onChange={e=>set('startsAt',e.target.value)}/></label><label>Date de fin<input type="date" value={form.endsAt} onChange={e=>set('endsAt',e.target.value)}/></label></div></section>
   <section className="promo-preview"><div className="promo-step"><span>6</span><div><b>Aperçu</b><small>Résumé avant enregistrement.</small></div></div><div className="promo-preview-card"><span>🎁 {form.name||'Nom de la promotion'}</span><strong>{preview()}</strong><small>{form.minOrder&&numeric(form.minOrder)>0?`Commande minimum : ${numeric(form.minOrder).toFixed(2).replace('.',',')} $`:'Aucun minimum de commande'}{form.maxUses?` · Max ${form.maxUses} utilisation(s) par client`:''}</small></div></section>
  </div><div className="promo-modal-actions"><button className="portal-secondary" onClick={()=>setOpen(false)}>Annuler</button><button className="portal-primary" disabled={saving} onClick={save}>{saving?'Enregistrement…':editing?'Enregistrer les modifications':'Créer la promotion'}</button></div></div></div>}
 </div>
}
