import {useEffect,useState} from 'react';
import './promotions.css';

type Promotion={id:string;name:string;description?:string|null;kind:'fixed'|'percent';value:number;trigger_type:'always'|'after_orders'|'first_orders';trigger_count:number;min_order_cents:number;starts_at?:string|null;ends_at?:string|null;max_uses_per_client?:number|null;uses_by_client:number;completed_orders:number;eligible:boolean;progress:number};
const money=(v:number)=>`${(v/100).toFixed(2).replace('.',',')} $`;
const reward=(p:Promotion)=>p.kind==='percent'?`${(p.value/100).toFixed(p.value%100===0?0:2).replace('.',',')} % de rabais`:`${money(p.value)} de rabais`;
const trigger=(p:Promotion)=>p.trigger_type==='after_orders'?`Après ${p.trigger_count} commande${p.trigger_count>1?'s':''}`:p.trigger_type==='first_orders'?`Sur les ${p.trigger_count} premières commandes`:'Offre générale';

export default function PromotionsPage(){
 const[promotions,setPromotions]=useState<Promotion[]>([]);const[completed,setCompleted]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{fetch('/api/client/promotions',{credentials:'same-origin',cache:'no-store'}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Impossible de charger les promotions.');setPromotions(d.promotions||[]);setCompleted(Number(d.completed_orders||0))}).catch(e=>setError(e instanceof Error?e.message:'Erreur')).finally(()=>setLoading(false))},[]);
 return <main className="promo-page"><header className="promo-top"><button onClick={()=>history.length>1?history.back():location.assign('/')} className="promo-back">←</button><div><span>FaisLaJob</span><h1>Offres spéciales</h1></div></header><section className="promo-hero"><div><span className="promo-kicker">🎁 Récompenses</span><h2>Plus tu utilises FaisLaJob, plus tu peux économiser.</h2><p>Tu as actuellement <strong>{completed} commande{completed!==1?'s':''} terminée{completed!==1?'s':''}</strong>.</p></div></section>{loading&&<div className="promo-state">Chargement des promotions…</div>}{error&&<div className="promo-error">⚠️ {error}</div>}{!loading&&!error&&promotions.length===0&&<section className="promo-empty"><div>🎉</div><h2>Aucune offre active pour le moment</h2><p>Les nouvelles promotions apparaîtront ici automatiquement.</p></section>}<section className="promo-grid">{promotions.map(p=><article className={`promo-card ${p.eligible?'eligible':'locked'}`} key={p.id}><div className="promo-card-head"><span className="promo-gift">{p.eligible?'🎉':'🎁'}</span><span className={`promo-status ${p.eligible?'on':''}`}>{p.eligible?'Disponible':'À débloquer'}</span></div><h3>{p.name}</h3><strong className="promo-value">{reward(p)}</strong>{p.description&&<p>{p.description}</p>}<div className="promo-rules"><span>{trigger(p)}</span>{p.min_order_cents>0&&<span>Commande minimum : {money(p.min_order_cents)}</span>}{p.ends_at&&<span>Valide jusqu’au {new Date(p.ends_at).toLocaleDateString('fr-CA')}</span>}{p.max_uses_per_client&&<span>Maximum {p.max_uses_per_client} utilisation{p.max_uses_per_client>1?'s':''} par client</span>}</div>{p.trigger_type==='after_orders'&&!p.eligible&&<div className="promo-progress"><div><span>Progression</span><strong>{Math.min(completed,p.trigger_count)}/{p.trigger_count}</strong></div><i><b style={{width:`${p.progress}%`}}/></i><small>Encore {Math.max(0,p.trigger_count-completed)} commande{Math.max(0,p.trigger_count-completed)!==1?'s':''} pour débloquer l’offre.</small></div>}</article>)}</section></main>;
}
