import { useEffect, useMemo, useState } from 'react';
import './request-native.css';

type User={id:string;email:string;role:'client'|'provider';client_id:string|null;provider_id:string|null;name:string;phone?:string|null};
type Category={id:string;icon:string;name:string;description:string;hourly_rate_cents?:number|null;subcategories:{name:string;icon:string;description:string}[]};
type ApiCategory={id:string;name:string;hourly_rate_cents:number|null};
type Place={display_name:string;lat:string;lon:string;address?:Record<string,string>};
type AddressFields={number:string;street:string;apartment:string;city:string;postalCode:string};
type ValidatedAddress={label:string;lat:number;lon:number}|null;

const initialCategories:Category[]=[
{id:'menage',icon:'🧹',name:'Ménage',description:'Maison, condo, nettoyage, etc.',subcategories:[{name:'Ménage régulier',icon:'🧹',description:'Entretien courant de la maison ou du condo'},{name:'Grand ménage',icon:'✨',description:'Nettoyage complet et en profondeur'},{name:'Après déménagement',icon:'📦',description:'Nettoyage après un départ ou une arrivée'}]},
{id:'reparations',icon:'🔧',name:'Petites réparations',description:'Plomberie, électricité, assemblage, etc.',subcategories:[{name:'Assemblage',icon:'🪛',description:'Meubles, étagères et petits assemblages'},{name:'Installation',icon:'🔧',description:'Petites installations à la maison'},{name:'Réparation légère',icon:'🛠️',description:'Petits travaux et réparations courantes'}]},
{id:'exterieur',icon:'🌿',name:'Terrain & extérieur',description:'Tonte, jardinage, entretien, etc.',subcategories:[{name:'Tonte de gazon',icon:'🌱',description:'Tonte et finition de la pelouse'},{name:'Ramassage de feuilles',icon:'🍂',description:'Ramassage et mise en sacs'},{name:'Entretien extérieur',icon:'🌿',description:'Petits travaux autour de la propriété'}]},
{id:'demenagement',icon:'📦',name:'Déménagement',description:'Résidentiel, commercial, transport, etc.',subcategories:[{name:'Aide à transporter',icon:'🏠',description:'Maison, condo ou appartement'},{name:'Chargement / déchargement',icon:'📦',description:'Quelques meubles ou boîtes seulement'},{name:'Petits meubles',icon:'🚚',description:'Transport de meubles et petits articles'}]},
{id:'deneigement',icon:'❄️',name:'Déneigement',description:'Entrée, trottoir, stationnement, etc.',subcategories:[{name:'Entrée',icon:'❄️',description:'Déneigement de l’entrée'},{name:'Escaliers',icon:'🧊',description:'Marches, galerie et accès'},{name:'Auto à déneiger',icon:'🚗',description:'Déneigement autour du véhicule'}]},
{id:'animaux',icon:'🐕',name:'Animaux',description:'Promenade, garde, aide ponctuelle, etc.',subcategories:[{name:'Promenade',icon:'🐕',description:'Promenade de ton animal'},{name:'Visite à domicile',icon:'🏡',description:'Visite, nourriture et présence'},{name:'Aide ponctuelle',icon:'🐾',description:'Besoin particulier pour ton animal'}]}
];
const timings=['Le plus tôt possible','Aujourd’hui','Cette semaine','Je choisis une date'];
const money=(cents?:number|null)=>typeof cents==='number'?`${(cents/100).toFixed(2).replace('.',',')} $`:'—';
const pricing=(c:Category)=>{const hourly=typeof c.hourly_rate_cents==='number'?c.hourly_rate_cents:null;return{hourly,minute:hourly===null?null:hourly/60,minimum:hourly===null?null:Math.ceil(hourly*15/60)}};

export default function RequestFlow(){
 const[categories,setCategories]=useState<Category[]>(initialCategories);
 const[step,setStep]=useState(0),[category,setCategory]=useState<Category|null>(null),[subcategory,setSubcategory]=useState('');
 const[details,setDetails]=useState(''),[timing,setTiming]=useState('');
 const[addressFields,setAddressFields]=useState<AddressFields>({number:'',street:'',apartment:'',city:'',postalCode:''});
 const[validatedAddress,setValidatedAddress]=useState<ValidatedAddress>(null),[addressLoading,setAddressLoading]=useState(false);
 const[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState('');
 const[user,setUser]=useState<User|null>(null),[missionId,setMissionId]=useState<string|null>(null),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false);
 useEffect(()=>{fetch('/api/auth/me',{credentials:'same-origin',cache:'no-store'}).then(async r=>{if(!r.ok)return;const u=(await r.json()).user as User;setUser(u);setName(u.name);setEmail(u.email);setPhone(u.phone||'')}).catch(()=>{})},[]);
 useEffect(()=>{fetch('/api/categories',{cache:'no-store'}).then(async r=>{if(!r.ok)return;const apiCategories=((await r.json()).categories||[]) as ApiCategory[];setCategories(current=>{const known=new Map(current.map(c=>[c.id,c]));return apiCategories.map(a=>{const base=known.get(a.id);return base?{...base,name:a.name,hourly_rate_cents:a.hourly_rate_cents}:{id:a.id,icon:'🧰',name:a.name,description:'Service offert par FaisLaJob',hourly_rate_cents:a.hourly_rate_cents,subcategories:[{name:'Service général',icon:'🧰',description:'Décris-nous la job et on trouvera le bon partenaire'}]}})});}).catch(()=>{})},[]);
 useEffect(()=>{if(!category)return;const fresh=categories.find(c=>c.id===category.id);if(fresh&&fresh!==category)setCategory(fresh)},[categories]);
 const title=useMemo(()=>['Qu’est-ce qu’on peut faire pour toi?',category?`Quel type de ${category.name.toLowerCase()}?`:'Choisis un service','Parle-nous un peu de la job','Quand as-tu besoin de quelqu’un?','Où la job doit-elle être faite?','Comment peut-on te joindre?','Vérifie ta demande'][step],[step,category]);
 const updateAddress=(key:keyof AddressFields,value:string)=>{setAddressFields(current=>({...current,[key]:value}));setValidatedAddress(null);setError('')};
 const displayAddress=(label:string)=>addressFields.apartment.trim()?`${label} — App. ${addressFields.apartment.trim()}`:label;
 const validateAddress=async()=>{
  const number=addressFields.number.trim(),street=addressFields.street.trim(),city=addressFields.city.trim(),postalCode=addressFields.postalCode.trim().toUpperCase();
  if(!number||!street||!city){setError('Entre le numéro, la rue et la ville avant de valider. Le code postal est facultatif.');return}
  setAddressLoading(true);setError('');setValidatedAddress(null);
  try{
   const params=new URLSearchParams({format:'jsonv2',addressdetails:'1',countrycodes:'ca',limit:'5',street:`${number} ${street}`,city,country:'Canada'});
   if(postalCode)params.set('postalcode',postalCode);
   const r=await fetch(`https://nominatim.openstreetmap.org/search?${params.toString()}`,{headers:{'Accept-Language':'fr-CA,fr;q=0.9'}});
   if(!r.ok)throw new Error();
   const places=await r.json() as Place[];
   const place=places[0];
   if(!place){setError('Adresse introuvable. Vérifie le numéro, la rue et la ville. Tu peux laisser le code postal vide.');return}
   if(postalCode){const a=place.address||{};const foundPostal=(a.postcode||'').replace(/\s/g,'').toUpperCase();const wantedPostal=postalCode.replace(/\s/g,'').toUpperCase();if(foundPostal&&wantedPostal&&foundPostal!==wantedPostal){setError('OpenStreetMap a trouvé l’adresse, mais le code postal ne correspond pas. Corrige-le ou laisse-le vide.');return}}
   setValidatedAddress({label:place.display_name,lat:Number(place.lat),lon:Number(place.lon)});
  }catch{setError('La validation OpenStreetMap est temporairement indisponible. Réessaie dans un instant.')}finally{setAddressLoading(false)}
 };
 const mapSrc=validatedAddress?`https://www.openstreetmap.org/export/embed.html?bbox=${validatedAddress.lon-.006}%2C${validatedAddress.lat-.004}%2C${validatedAddress.lon+.006}%2C${validatedAddress.lat+.004}&layer=mapnik&marker=${validatedAddress.lat}%2C${validatedAddress.lon}`:'';
 const submit=async()=>{if(!category||!validatedAddress)return;setSubmitting(true);setError('');try{let clientId:number|undefined;if(user?.role==='client'&&user.client_id)clientId=Number(user.client_id);else{const cr=await fetch('/api/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,phone})});if(!cr.ok)throw new Error('Création du client impossible.');clientId=Number((await cr.json()).client.id)}const description=[subcategory,details,`Moment: ${timing}`,`Adresse: ${displayAddress(validatedAddress.label)}`,addressFields.postalCode.trim()?`Code postal saisi: ${addressFields.postalCode.trim().toUpperCase()}`:'',`Coordonnées: ${validatedAddress.lat}, ${validatedAddress.lon}`].filter(Boolean).join('\n');const mr=await fetch('/api/missions',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,categoryId:category.id,description})});if(!mr.ok)throw new Error('Création de la mission impossible.');setMissionId(String((await mr.json()).mission.id))}catch(e){setError(e instanceof Error?e.message:'Une erreur est survenue.')}finally{setSubmitting(false)}};
 const back=()=>{if(step===0){window.location.href='/';return}setStep(s=>Math.max(0,s-1))};
 const selectedPricing=category?pricing(category):null;
 if(missionId)return <main className="request-native-shell"><section className="request-native-card request-success"><div className="request-kicker">Demande envoyée</div><div className="request-success-icon">✓</div><h1>Ta demande est partie!</h1><p>Mission #{missionId} créée avec succès. On cherche maintenant le bon partenaire.</p><button className="request-primary" onClick={()=>window.location.href='/'}>Retour à l’accueil</button></section></main>;
 return <main className="request-native-shell"><header className="request-native-header"><button onClick={()=>window.location.href='/'} className="request-brand">FaisLaJob</button>{user&&<span className="request-user-chip">{user.name}</span>}</header><section className="request-native-card"><div className="request-topline"><button className="request-back" onClick={back}>←</button><div className="request-kicker">{category&&step>0?`${category.icon} ${category.name}`:'Demande de service'}</div><span className="request-step">Étape {step+1}/7</span></div><div className="request-progress"><span style={{width:`${((step+1)/7)*100}%`}}/></div><h1>{title}</h1>{step===0&&user?.role==='client'&&<div className="request-account-note">🛡️ Connecté comme <strong>{user.name}</strong> — ta demande sera liée automatiquement à ton compte.</div>}{step===0&&<><p className="request-copy">Choisis une catégorie. Les tarifs sont affichés avant d’envoyer ta demande.</p><div className="request-category-grid">{categories.map(c=>{const p=pricing(c);return <button key={c.id} className={`request-category ${category?.id===c.id?'selected':''}`} onClick={()=>{setCategory(c);setSubcategory('');setStep(1)}}><span className="request-category-icon">{c.icon}</span><span className="request-category-copy"><strong>{c.name}</strong><small>{c.description}</small>{p.hourly!==null&&<small><b>{money(p.minute)}/min · {money(p.hourly)}/h</b><br/>Minimum 15 min : {money(p.minimum)}</small>}</span><span className="request-chevron">›</span></button>})}</div><button className="request-help-category">◉ Je ne trouve pas ma catégorie <span>›</span></button></>}
 {step===1&&category&&<><p className="request-copy">Choisis l’option qui décrit le mieux.</p>{selectedPricing?.hourly!==null&&<div className="request-tip">💵 <span><strong>{money(selectedPricing.minute)}/minute · {money(selectedPricing.hourly)}/heure</strong><br/>Minimum facturable de 15 minutes : <strong>{money(selectedPricing.minimum)}</strong></span></div>}<div className="request-option-list">{category.subcategories.map(o=><button key={o.name} className={`request-option ${subcategory===o.name?'selected':''}`} onClick={()=>setSubcategory(o.name)}><span className="request-option-icon">{o.icon}</span><span className="request-option-copy"><strong>{o.name}</strong><small>{o.description}</small></span><span className="request-radio">{subcategory===o.name?'●':'○'}</span></button>)}</div><div className="request-tip">💡 <span><strong>Bon à savoir</strong><br/>Tu pourras donner plus de détails à l’étape suivante pour recevoir un prix juste.</span></div><button className="request-primary" disabled={!subcategory} onClick={()=>setStep(2)}>Continuer →</button></>}
 {step===2&&<><p className="request-copy">Explique-nous simplement ce qu’il faut faire.</p><textarea className="request-textarea" rows={6} value={details} placeholder="Ex. J’ai un divan et une commode à déplacer du 2e étage..." onChange={e=>setDetails(e.target.value)}/><button className="request-primary" disabled={details.trim().length<5} onClick={()=>setStep(3)}>Continuer →</button></>}
 {step===3&&<><p className="request-copy">Choisis le moment qui te convient.</p><div className="request-option-list">{timings.map(t=><button key={t} className={`request-option compact ${timing===t?'selected':''}`} onClick={()=>setTiming(t)}><span className="request-option-icon">⏱️</span><span className="request-option-copy"><strong>{t}</strong></span><span className="request-radio">{timing===t?'●':'○'}</span></button>)}</div><button className="request-primary" disabled={!timing} onClick={()=>setStep(4)}>Continuer →</button></>}
 {step===4&&<><p className="request-copy">Entre l’adresse de la job. OpenStreetMap va la valider avant de continuer. Le code postal et l’appartement sont facultatifs.</p><div className="request-address-grid"><label className="request-field request-field-number"><span>Numéro</span><input value={addressFields.number} inputMode="numeric" placeholder="123" onChange={e=>updateAddress('number',e.target.value)}/></label><label className="request-field request-field-street"><span>Nom de rue</span><input value={addressFields.street} placeholder="Rue des Forges" onChange={e=>updateAddress('street',e.target.value)}/></label><label className="request-field request-field-apartment"><span>Appartement <small>(facultatif)</small></span><input value={addressFields.apartment} placeholder="4B" onChange={e=>updateAddress('apartment',e.target.value)}/></label><label className="request-field request-field-city"><span>Ville</span><input value={addressFields.city} placeholder="Trois-Rivières" onChange={e=>updateAddress('city',e.target.value)}/></label><label className="request-field request-field-postal"><span>Code postal <small>(facultatif)</small></span><input value={addressFields.postalCode} autoCapitalize="characters" placeholder="G9A 2G7" maxLength={7} onChange={e=>updateAddress('postalCode',e.target.value.toUpperCase())}/></label></div><button className="request-validate-address" disabled={addressLoading} onClick={validateAddress}>{addressLoading?'⏳ Validation…':'✓ Valider l’adresse'}</button>{validatedAddress&&<div className="request-address-confirm"><div className="request-address-confirm-head"><span>✓</span><div><strong>Adresse validée par OpenStreetMap</strong><small>{displayAddress(validatedAddress.label)}</small></div></div><div className="request-map"><iframe title="Adresse de la job sur OpenStreetMap" loading="lazy" src={mapSrc}/><div className="request-map-credit">Carte © contributeurs OpenStreetMap</div></div></div>}<button className="request-primary" disabled={!validatedAddress} onClick={()=>setStep(user?.role==='client'?6:5)}>Continuer →</button></>}
 {step===5&&<><p className="request-copy">Tes coordonnées servent seulement à organiser la mission.</p><input className="request-input" value={name} placeholder="Nom complet" onChange={e=>setName(e.target.value)}/><input className="request-input" value={email} placeholder="Courriel" onChange={e=>setEmail(e.target.value)}/><input className="request-input" value={phone} placeholder="Téléphone" onChange={e=>setPhone(e.target.value)}/><button className="request-primary" disabled={name.trim().length<2||(!email.trim()&&!phone.trim())} onClick={()=>setStep(6)}>Voir le résumé →</button></>}
 {step===6&&category&&<><div className="request-summary"><div><span>Service</span><strong>{category.name}</strong></div><div><span>Type</span><strong>{subcategory}</strong></div><div><span>Quand</span><strong>{timing}</strong></div><div><span>Adresse</span><strong>{validatedAddress?displayAddress(validatedAddress.label):'—'}</strong></div>{selectedPricing?.hourly!==null&&<><div><span>Tarif</span><strong>{money(selectedPricing.minute)}/min · {money(selectedPricing.hourly)}/h</strong></div><div><span>Minimum</span><strong>15 min · {money(selectedPricing.minimum)}</strong></div></>}<div className="wide"><span>Détails</span><strong>{details}</strong></div></div>{validatedAddress&&<div className="request-map request-summary-map"><iframe title="Adresse de la job sur OpenStreetMap" loading="lazy" src={mapSrc}/><div className="request-map-credit">Carte © contributeurs OpenStreetMap</div></div>}<button className="request-primary" disabled={submitting||!validatedAddress} onClick={submit}>{submitting?'Envoi…':'Trouver un partenaire →'}</button></>}{error&&<div className="request-error">⚠️ {error}</div>}</section></main>;
}
