import { useEffect, useMemo, useState } from 'react';
import './request-native.css';

type User={id:string;email:string;role:'client'|'provider';client_id:string|null;provider_id:string|null;name:string;phone?:string|null};
type Category={id:string;icon:string;name:string;description:string;subcategories:{name:string;icon:string;description:string}[]};
type Place={display_name:string;lat:string;lon:string;address?:Record<string,string>};

const categories:Category[]=[
{id:'menage',icon:'🧹',name:'Ménage',description:'Maison, condo, nettoyage, etc.',subcategories:[{name:'Ménage régulier',icon:'🧹',description:'Entretien courant de la maison ou du condo'},{name:'Grand ménage',icon:'✨',description:'Nettoyage complet et en profondeur'},{name:'Après déménagement',icon:'📦',description:'Nettoyage après un départ ou une arrivée'}]},
{id:'reparations',icon:'🔧',name:'Petites réparations',description:'Plomberie, électricité, assemblage, etc.',subcategories:[{name:'Assemblage',icon:'🪛',description:'Meubles, étagères et petits assemblages'},{name:'Installation',icon:'🔧',description:'Petites installations à la maison'},{name:'Réparation légère',icon:'🛠️',description:'Petits travaux et réparations courantes'}]},
{id:'exterieur',icon:'🌿',name:'Terrain & extérieur',description:'Tonte, jardinage, entretien, etc.',subcategories:[{name:'Tonte de gazon',icon:'🌱',description:'Tonte et finition de la pelouse'},{name:'Ramassage de feuilles',icon:'🍂',description:'Ramassage et mise en sacs'},{name:'Entretien extérieur',icon:'🌿',description:'Petits travaux autour de la propriété'}]},
{id:'demenagement',icon:'📦',name:'Déménagement',description:'Résidentiel, commercial, transport, etc.',subcategories:[{name:'Aide à transporter',icon:'🏠',description:'Maison, condo ou appartement'},{name:'Chargement / déchargement',icon:'📦',description:'Quelques meubles ou boîtes seulement'},{name:'Petits meubles',icon:'🚚',description:'Transport de meubles et petits articles'}]},
{id:'deneigement',icon:'❄️',name:'Déneigement',description:'Entrée, trottoir, stationnement, etc.',subcategories:[{name:'Entrée',icon:'❄️',description:'Déneigement de l’entrée'},{name:'Escaliers',icon:'🧊',description:'Marches, galerie et accès'},{name:'Auto à déneiger',icon:'🚗',description:'Déneigement autour du véhicule'}]},
{id:'animaux',icon:'🐕',name:'Animaux',description:'Promenade, garde, aide ponctuelle, etc.',subcategories:[{name:'Promenade',icon:'🐕',description:'Promenade de ton animal'},{name:'Visite à domicile',icon:'🏡',description:'Visite, nourriture et présence'},{name:'Aide ponctuelle',icon:'🐾',description:'Besoin particulier pour ton animal'}]}
];
const timings=['Le plus tôt possible','Aujourd’hui','Cette semaine','Je choisis une date'];

function shortPlace(p:Place){const a=p.address||{};const street=[a.house_number,a.road].filter(Boolean).join(' ');const city=a.city||a.town||a.village||a.municipality||'';return [street||p.display_name.split(',')[0],city,a.state].filter(Boolean).join(', ')}

export default function RequestFlow(){
 const[step,setStep]=useState(0),[category,setCategory]=useState<Category|null>(null),[subcategory,setSubcategory]=useState('');
 const[details,setDetails]=useState(''),[timing,setTiming]=useState(''),[address,setAddress]=useState('');
 const[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState('');
 const[user,setUser]=useState<User|null>(null),[missionId,setMissionId]=useState<string|null>(null),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false);
 const[suggestions,setSuggestions]=useState<Place[]>([]),[addressLoading,setAddressLoading]=useState(false),[locating,setLocating]=useState(false);
 useEffect(()=>{fetch('/api/auth/me',{credentials:'same-origin',cache:'no-store'}).then(async r=>{if(!r.ok)return;const u=(await r.json()).user as User;setUser(u);setName(u.name);setEmail(u.email);setPhone(u.phone||'')}).catch(()=>{})},[]);
 useEffect(()=>{if(step!==4||address.trim().length<3){setSuggestions([]);return}const t=window.setTimeout(async()=>{setAddressLoading(true);try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&countrycodes=ca&limit=5&q=${encodeURIComponent(address)}`,{headers:{'Accept-Language':'fr-CA,fr;q=0.9'}});if(r.ok)setSuggestions(await r.json())}catch{}finally{setAddressLoading(false)}},350);return()=>window.clearTimeout(t)},[address,step]);
 const title=useMemo(()=>['Qu’est-ce qu’on peut faire pour toi?',category?`Quel type de ${category.name.toLowerCase()}?`:'Choisis un service','Parle-nous un peu de la job','Quand as-tu besoin de quelqu’un?','Où la job doit-elle être faite?','Comment peut-on te joindre?','Vérifie ta demande'][step],[step,category]);
 const chooseLocation=()=>{if(!navigator.geolocation){setError('La localisation n’est pas disponible sur cet appareil.');return}setLocating(true);setError('');navigator.geolocation.getCurrentPosition(async p=>{try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&lat=${p.coords.latitude}&lon=${p.coords.longitude}`,{headers:{'Accept-Language':'fr-CA,fr;q=0.9'}});const place=await r.json() as Place;setAddress(place.display_name||`${p.coords.latitude}, ${p.coords.longitude}`);setSuggestions([])}catch{setError('Impossible de trouver l’adresse de ta position.')}finally{setLocating(false)}},()=>{setLocating(false);setError('Autorise la localisation pour utiliser ta position.')},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})};
 const submit=async()=>{if(!category)return;setSubmitting(true);setError('');try{let clientId:number|undefined;if(user?.role==='client'&&user.client_id)clientId=Number(user.client_id);else{const cr=await fetch('/api/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,phone})});if(!cr.ok)throw new Error('Création du client impossible.');clientId=Number((await cr.json()).client.id)}const description=[subcategory,details,`Moment: ${timing}`,`Adresse: ${address}`].join('\n');const mr=await fetch('/api/missions',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,categoryId:category.id,description})});if(!mr.ok)throw new Error('Création de la mission impossible.');setMissionId(String((await mr.json()).mission.id))}catch(e){setError(e instanceof Error?e.message:'Une erreur est survenue.')}finally{setSubmitting(false)}};
 const back=()=>{if(step===0){window.location.href='/';return}setStep(s=>Math.max(0,s-1))};
 if(missionId)return <main className="request-native-shell"><section className="request-native-card request-success"><div className="request-kicker">Demande envoyée</div><div className="request-success-icon">✓</div><h1>Ta demande est partie!</h1><p>Mission #{missionId} créée avec succès. On cherche maintenant le bon partenaire.</p><button className="request-primary" onClick={()=>window.location.href='/'}>Retour à l’accueil</button></section></main>;
 return <main className="request-native-shell"><header className="request-native-header"><button onClick={()=>window.location.href='/'} className="request-brand">FaisLaJob</button>{user&&<span className="request-user-chip">{user.name}</span>}</header><section className="request-native-card"><div className="request-topline"><button className="request-back" onClick={back}>←</button><div className="request-kicker">{category&&step>0?`${category.icon} ${category.name}`:'Demande de service'}</div><span className="request-step">Étape {step+1}/7</span></div><div className="request-progress"><span style={{width:`${((step+1)/7)*100}%`}}/></div><h1>{title}</h1>{step===0&&user?.role==='client'&&<div className="request-account-note">🛡️ Connecté comme <strong>{user.name}</strong> — ta demande sera liée automatiquement à ton compte.</div>}{step===0&&<><p className="request-copy">Choisis une catégorie. Ensuite, on te pose seulement les questions utiles.</p><div className="request-category-grid">{categories.map(c=><button key={c.id} className={`request-category ${category?.id===c.id?'selected':''}`} onClick={()=>{setCategory(c);setSubcategory('');setStep(1)}}><span className="request-category-icon">{c.icon}</span><span className="request-category-copy"><strong>{c.name}</strong><small>{c.description}</small></span><span className="request-chevron">›</span></button>)}</div><button className="request-help-category">◉ Je ne trouve pas ma catégorie <span>›</span></button></>}
 {step===1&&category&&<><p className="request-copy">Choisis l’option qui décrit le mieux.</p><div className="request-option-list">{category.subcategories.map(o=><button key={o.name} className={`request-option ${subcategory===o.name?'selected':''}`} onClick={()=>setSubcategory(o.name)}><span className="request-option-icon">{o.icon}</span><span className="request-option-copy"><strong>{o.name}</strong><small>{o.description}</small></span><span className="request-radio">{subcategory===o.name?'●':'○'}</span></button>)}</div><div className="request-tip">💡 <span><strong>Bon à savoir</strong><br/>Tu pourras donner plus de détails à l’étape suivante pour recevoir un prix juste.</span></div><button className="request-primary" disabled={!subcategory} onClick={()=>setStep(2)}>Continuer →</button></>}
 {step===2&&<><p className="request-copy">Explique-nous simplement ce qu’il faut faire.</p><textarea className="request-textarea" rows={6} value={details} placeholder="Ex. J’ai un divan et une commode à déplacer du 2e étage..." onChange={e=>setDetails(e.target.value)}/><button className="request-primary" disabled={details.trim().length<5} onClick={()=>setStep(3)}>Continuer →</button></>}
 {step===3&&<><p className="request-copy">Choisis le moment qui te convient.</p><div className="request-option-list">{timings.map(t=><button key={t} className={`request-option compact ${timing===t?'selected':''}`} onClick={()=>setTiming(t)}><span className="request-option-icon">⏱️</span><span className="request-option-copy"><strong>{t}</strong></span><span className="request-radio">{timing===t?'●':'○'}</span></button>)}</div><button className="request-primary" disabled={!timing} onClick={()=>setStep(4)}>Continuer →</button></>}
 {step===4&&<><p className="request-copy">Entre l’adresse ou utilise ta position.</p><button className="request-locate" onClick={chooseLocation} disabled={locating}>📍 {locating?'Localisation…':'Utiliser ma position'}</button><div className="request-address-wrap"><input className="request-input" value={address} placeholder="Commence à écrire ton adresse…" onChange={e=>setAddress(e.target.value)}/>{addressLoading&&<div className="request-address-status">Recherche…</div>}{suggestions.length>0&&<div className="request-suggestions">{suggestions.map((p,i)=><button key={`${p.lat}-${p.lon}-${i}`} onClick={()=>{setAddress(p.display_name);setSuggestions([])}}><strong>{shortPlace(p)}</strong><small>{p.display_name}</small></button>)}</div>}</div><button className="request-primary" disabled={address.trim().length<5} onClick={()=>setStep(user?.role==='client'?6:5)}>Continuer →</button></>}
 {step===5&&<><p className="request-copy">Tes coordonnées servent seulement à organiser la mission.</p><input className="request-input" value={name} placeholder="Nom complet" onChange={e=>setName(e.target.value)}/><input className="request-input" value={email} placeholder="Courriel" onChange={e=>setEmail(e.target.value)}/><input className="request-input" value={phone} placeholder="Téléphone" onChange={e=>setPhone(e.target.value)}/><button className="request-primary" disabled={name.trim().length<2||(!email.trim()&&!phone.trim())} onClick={()=>setStep(6)}>Voir le résumé →</button></>}
 {step===6&&category&&<><div className="request-summary"><div><span>Service</span><strong>{category.name}</strong></div><div><span>Type</span><strong>{subcategory}</strong></div><div><span>Quand</span><strong>{timing}</strong></div><div><span>Adresse</span><strong>{address}</strong></div><div className="wide"><span>Détails</span><strong>{details}</strong></div></div><button className="request-primary" disabled={submitting} onClick={submit}>{submitting?'Envoi…':'Trouver un partenaire →'}</button></>}{error&&<div className="request-error">⚠️ {error}</div>}</section></main>;
}
