import { useEffect, useState } from 'react';

type User={id:string;email:string;role:'client'|'provider';client_id:string|null;provider_id:string|null;name:string;phone?:string|null};
type ClientMission={id:string;category_name:string;status:string;description:string;duration_minutes?:number|null;client_total_cents?:number|null;billable_minutes?:number|null;billing_status?:string|null;payment_status?:string|null;created_at:string;completed_at?:string|null};
type Provider={id:string;name:string;email?:string;phone?:string;status:string;is_online:boolean;category_ids?:string[]};
type Offer={offer_id:string;mission_id:string;category_name:string;description:string;mission_status:string;offered_at?:string};
type Mission={id:string;provider_id:string|null;category_name?:string;category_id:string;status:string;description:string;duration_minutes?:number|null;created_at?:string;started_at?:string;completed_at?:string};
type Payout={id:string;mission_id:string;category_name:string;amount_cents:number;status:string;release_at?:string|null;created_at?:string};
type Billing={mission_id:string;actual_minutes:number;billable_minutes:number;subtotal_cents:number;client_service_fee_cents:number;client_total_cents:number;provider_net_cents:number;payment_status?:string;payment_method?:string;payout_status?:string;release_at?:string|null};

const cats=['menage','reparations','exterieur','demenagement','deneigement','animaux'];
const money=(v?:number|null)=>typeof v==='number'?`${(v/100).toFixed(2).replace('.',',')} $`:'—';
const statusLabel:Record<string,string>={requested:'Recherche',offered:'Offerte',assigned:'Partenaire trouvé',en_route:'En route',arrived:'Arrivé',in_progress:'En cours',completed:'Terminée',cancelled:'Annulée'};
const statusIcon:Record<string,string>={requested:'🔎',offered:'📣',assigned:'🤝',en_route:'🚗',arrived:'📍',in_progress:'🛠️',completed:'✅',cancelled:'✖️'};

export default function UserPortal({user,onLogout}:{user:User;onLogout:()=>void}){
  return user.role==='client'?<ClientPortal user={user} onLogout={onLogout}/>:<ProviderPortal user={user} onLogout={onLogout}/>;
}

function Shell({user,role,tab,setTab,onLogout,children}:{user:User;role:'client'|'provider';tab:string;setTab:(v:any)=>void;onLogout:()=>void;children:any}){
  const items=role==='client'?[['home','⌂','Accueil'],['missions','📋','Mes missions'],['payments','💳','Paiements'],['profile','👤','Profil']]:[['home','⌂','Accueil'],['jobs','⚡','Jobs'],['mission','🧭','Mission active'],['earnings','💰','Revenus'],['profile','👤','Profil']];
  const defaultTab=role==='provider'?'jobs':'home';
  return <main className="user-portal-shell"><aside className="user-portal-nav"><button className="brand brand-button portal-brand" onClick={()=>setTab(defaultTab)}>FaisLaJob</button><div className="portal-role">{role==='client'?'Portail client':'Portail partenaire'}</div><nav>{items.map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span>{label}</button>)}</nav><div className="portal-user"><div className="avatar">{user.name?.[0]?.toUpperCase()||'F'}</div><div><strong>{user.name}</strong><span>{user.email}</span></div></div><button className="portal-logout" onClick={onLogout}>Déconnexion</button></aside><section className="user-portal-main">{children}</section></main>;
}

function ClientPortal({user,onLogout}:{user:User;onLogout:()=>void}){
 const[tab,setTab]=useState('home');const[missions,setMissions]=useState<ClientMission[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[billing,setBilling]=useState<Billing|null>(null);
 const load=async(background=false)=>{if(!background)setLoading(true);if(!background)setError('');try{const r=await fetch('/api/client/missions',{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error('Impossible de charger tes missions.');setMissions((await r.json()).missions||[])}catch(e){if(!background)setError(e instanceof Error?e.message:'Erreur')}finally{if(!background)setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(()=>load(true),4000);return()=>clearInterval(t)},[]);
 const active=missions.find(m=>!['completed','cancelled'].includes(m.status));
 const completed=missions.filter(m=>m.status==='completed');
 const paid=missions.filter(m=>m.payment_status==='paid');
 const spent=paid.reduce((s,m)=>s+Number(m.client_total_cents||0),0);
 const viewBilling=async(id:string)=>{setError('');const r=await fetch(`/api/missions/${id}/billing`,{credentials:'same-origin'});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Facture indisponible.');return}setBilling(d.billing)};
 const pay=async(id:string)=>{const r=await fetch(`/api/missions/${id}/pay/mock`,{method:'POST',credentials:'same-origin'});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Paiement impossible.');return}setBilling(d.billing);await load(true)};
 return <Shell user={user} role="client" tab={tab} setTab={setTab} onLogout={onLogout}>
  <header className="portal-top"><div><span className="portal-kicker">Bonjour {user.name.split(' ')[0]} 👋</span><h1>{tab==='home'?'Ton tableau de bord':tab==='missions'?'Tes missions':tab==='payments'?'Paiements & factures':'Ton profil'}</h1></div><div style={{display:'flex',gap:10,flexWrap:'wrap',justifyContent:'flex-end'}}><button className="portal-secondary" onClick={onLogout}>Déconnexion</button><button className="portal-primary" onClick={()=>window.location.href='/request'}>＋ Nouvelle demande</button></div></header>
  {error&&<div className="portal-alert">⚠️ {error}</div>}
  {tab==='home'&&<><div className="portal-stats"><Stat label="Mission active" value={active?'1':'0'} hint={active?statusLabel[active.status]:'Aucune en cours'}/><Stat label="Missions terminées" value={String(completed.length)} hint="Historique"/><Stat label="Total payé" value={money(spent)} hint={`${paid.length} paiement${paid.length!==1?'s':''}`}/></div>{active?<section className="portal-feature"><div className="feature-icon">{statusIcon[active.status]||'📋'}</div><div><span className="portal-kicker">Mission #{active.id} • {active.category_name}</span><h2>{statusLabel[active.status]||active.status}</h2><p>{active.description}</p></div><button onClick={()=>setTab('missions')}>Voir le suivi →</button></section>:<section className="portal-empty-big"><div>✨</div><h2>Besoin d’un coup de main?</h2><p>Crée une demande et on cherche un partenaire disponible.</p><button className="portal-primary" onClick={()=>window.location.href='/request'}>Trouver quelqu’un</button></section>}<Recent missions={missions.slice(0,4)} onBilling={viewBilling}/></>}
  {tab==='missions'&&<section className="portal-panel"><div className="panel-head"><div><span className="portal-kicker">Historique</span><h2>Toutes tes missions</h2></div><button className="portal-secondary" onClick={()=>load(false)}>↻ Actualiser</button></div>{loading&&missions.length===0?<p>Chargement…</p>:missions.length===0?<p className="portal-empty">Aucune mission.</p>:<div className="portal-list">{missions.map(m=><MissionRow key={m.id} mission={m} onBilling={viewBilling} onPay={pay}/>)}</div>}</section>}
  {tab==='payments'&&<section className="portal-panel"><div className="panel-head"><div><span className="portal-kicker">Finance</span><h2>Factures et paiements</h2></div></div><div className="portal-list">{completed.length===0?<p className="portal-empty">Aucune facture disponible.</p>:completed.map(m=><MissionRow key={m.id} mission={m} onBilling={viewBilling} onPay={pay} compact/>)}</div></section>}
  {tab==='profile'&&<ProfileCard user={user} role="client"/>}
  {billing&&<BillingModal billing={billing} close={()=>setBilling(null)} pay={()=>pay(String(billing.mission_id))}/>} 
 </Shell>
}

function ProviderPortal({user,onLogout}:{user:User;onLogout:()=>void}){
 const[tab,setTab]=useState('jobs');const[provider,setProvider]=useState<Provider|null>(null);const[offers,setOffers]=useState<Offer[]>([]);const[mission,setMission]=useState<Mission|null>(null);const[payouts,setPayouts]=useState<Payout[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const id=user.provider_id;
 const load=async(background=false)=>{if(!id)return;if(!background)setLoading(true);try{const [pr,or,pa]=await Promise.all([fetch(`/api/providers/${id}`,{credentials:'same-origin',cache:'no-store'}),fetch(`/api/providers/${id}/offers`,{credentials:'same-origin',cache:'no-store'}),fetch('/api/provider/payouts',{credentials:'same-origin',cache:'no-store'})]);if(pr.ok)setProvider((await pr.json()).provider);if(or.ok)setOffers((await or.json()).offers||[]);if(pa.ok)setPayouts((await pa.json()).payouts||[]);const stored=localStorage.getItem(`faislajob_active_mission_${id}`);if(stored){const mr=await fetch(`/api/missions/${stored}`,{credentials:'same-origin',cache:'no-store'});if(mr.ok){const m=(await mr.json()).mission as Mission;if(m.status==='completed'){setMission(null);localStorage.removeItem(`faislajob_active_mission_${id}`)}else setMission(m)}}}catch(e){if(!background)setError(e instanceof Error?e.message:'Erreur partenaire')}finally{if(!background)setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(()=>load(true),4000);return()=>clearInterval(t)},[id]);
 const toggle=async()=>{if(!id||!provider)return;await fetch(`/api/providers/${id}/availability`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({online:!provider.is_online,categoryIds:cats})});await load(true)};
 const accept=async(offerId:string)=>{const r=await fetch(`/api/offers/${offerId}/accept`,{method:'POST',credentials:'same-origin'});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Mission non disponible.');return}setMission(d.mission);localStorage.setItem(`faislajob_active_mission_${id}`,d.mission.id);setTab('mission');await load(true)};
 const decline=async(offerId:string)=>{await fetch(`/api/offers/${offerId}/decline`,{method:'POST',credentials:'same-origin'});await load(true)};
 const act=async(action:'en-route'|'arrive'|'start'|'complete')=>{if(!mission)return;const r=await fetch(`/api/missions/${mission.id}/${action}`,{method:'POST',credentials:'same-origin'});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Action impossible.');return}if(d.mission.status==='completed'){localStorage.removeItem(`faislajob_active_mission_${id}`);setMission(null);setTab('earnings')}else setMission(d.mission);await load(true)};
 const total=payouts.reduce((s,p)=>s+Number(p.amount_cents||0),0),paid=payouts.filter(p=>p.status==='paid').reduce((s,p)=>s+Number(p.amount_cents||0),0),pending=total-paid;
 return <Shell user={user} role="provider" tab={tab} setTab={setTab} onLogout={onLogout}>
  <header className="portal-top"><div><span className="portal-kicker">Portail partenaire</span><h1>{tab==='home'?'Prêt à faire des jobs?':tab==='jobs'?'Jobs disponibles':tab==='mission'?'Mission active':tab==='earnings'?'Tes revenus':'Ton profil'}</h1></div><div style={{display:'flex',gap:10,flexWrap:'wrap',justifyContent:'flex-end'}}><button className="portal-secondary" onClick={onLogout}>Déconnexion</button><button className={`online-toggle ${provider?.is_online?'online':''}`} onClick={toggle}>{provider?.is_online?'● En ligne':'○ Hors ligne'}</button></div></header>
  {error&&<div className="portal-alert">⚠️ {error}</div>}
  {tab==='home'&&<><div className="portal-stats"><Stat label="Jobs disponibles" value={String(offers.length)} hint={provider?.is_online?'Tu es visible':'Mets-toi en ligne'}/><Stat label="Mission active" value={mission?'1':'0'} hint={mission?statusLabel[mission.status]:'Aucune'}/><Stat label="Revenus" value={money(total)} hint={`${money(pending)} en traitement`}/></div>{mission?<ActiveMission mission={mission} act={act}/>:offers[0]?<section className="portal-feature"><div className="feature-icon">⚡</div><div><span className="portal-kicker">Nouvelle offre • Mission #{offers[0].mission_id}</span><h2>{offers[0].category_name}</h2><p>{offers[0].description}</p></div><button onClick={()=>setTab('jobs')}>Voir les jobs →</button></section>:<section className="portal-empty-big"><div>{provider?.is_online?'📡':'🌙'}</div><h2>{provider?.is_online?'Tu es en ligne':'Tu es hors ligne'}</h2><p>{provider?.is_online?'On t’affichera les nouvelles jobs ici dès qu’elles arrivent.':'Mets-toi en ligne pour recevoir des offres.'}</p>{!provider?.is_online&&<button className="portal-primary" onClick={toggle}>Me mettre en ligne</button>}</section>}</>}
  {tab==='jobs'&&<section className="portal-panel"><div className="panel-head"><div><span className="portal-kicker">Radar</span><h2>{offers.length} job{offers.length!==1?'s':''} disponible{offers.length!==1?'s':''}</h2></div><button className="portal-secondary" onClick={()=>load(false)}>↻ Actualiser</button></div>{loading&&offers.length===0?<p>Chargement…</p>:offers.length===0?<p className="portal-empty">Aucune offre pour le moment.</p>:<div className="portal-list">{offers.map(o=><article className="job-card" key={o.offer_id}><div><span className="portal-kicker">Mission #{o.mission_id}</span><h3>{o.category_name}</h3><p>{o.description}</p></div><div className="job-actions"><button className="portal-primary" onClick={()=>accept(o.offer_id)}>Accepter</button><button className="portal-secondary" onClick={()=>decline(o.offer_id)}>Refuser</button></div></article>)}</div>}</section>}
  {tab==='mission'&&(mission?<ActiveMission mission={mission} act={act}/>:<section className="portal-empty-big"><div>🧭</div><h2>Aucune mission active</h2><p>Accepte une offre pour commencer.</p><button className="portal-primary" onClick={()=>setTab('jobs')}>Voir les jobs</button></section>)}
  {tab==='earnings'&&<section className="portal-panel"><div className="portal-stats"><Stat label="Total généré" value={money(total)} hint="Toutes missions"/><Stat label="Payé" value={money(paid)} hint="Versements complétés"/><Stat label="En traitement" value={money(pending)} hint="Retenues et attente"/></div><div className="panel-head"><div><span className="portal-kicker">Historique</span><h2>Mes versements</h2></div></div><div className="portal-list">{payouts.length===0?<p className="portal-empty">Aucun versement.</p>:payouts.map(p=><article className="payout-row" key={p.id}><div><strong>Mission #{p.mission_id} • {p.category_name}</strong><span>{p.release_at?`Libération prévue ${new Date(p.release_at).toLocaleDateString('fr-CA')}`:'Versement enregistré'}</span></div><div><strong>{money(p.amount_cents)}</strong><span className="portal-badge">{p.status}</span></div></article>)}</div></section>}
  {tab==='profile'&&<><ProfileCard user={user} role="provider"/><section className="portal-panel"><div className="panel-head"><div><span className="portal-kicker">Disponibilité</span><h2>Statut partenaire</h2></div></div><div className="profile-lines"><div><span>Compte</span><strong>{provider?.status||'active'}</strong></div><div><span>Disponibilité</span><strong>{provider?.is_online?'🟢 En ligne':'⚪ Hors ligne'}</strong></div><div><span>Catégories</span><strong>{provider?.category_ids?.length||cats.length}</strong></div></div></section></>}
 </Shell>
}

function Stat({label,value,hint}:{label:string;value:string;hint:string}){return <div className="portal-stat"><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>}
function Recent({missions,onBilling}:{missions:ClientMission[];onBilling:(id:string)=>void}){return <section className="portal-panel"><div className="panel-head"><div><span className="portal-kicker">Récent</span><h2>Dernières missions</h2></div></div>{missions.length===0?<p className="portal-empty">Aucune mission.</p>:<div className="portal-list">{missions.map(m=><MissionRow key={m.id} mission={m} onBilling={onBilling}/>)}</div>}</section>}
function MissionRow({mission,onBilling,onPay,compact}:{mission:ClientMission;onBilling:(id:string)=>void;onPay?:(id:string)=>void;compact?:boolean}){return <article className="mission-row"><div className="mission-row-icon">{statusIcon[mission.status]||'📋'}</div><div className="mission-row-main"><span className="portal-kicker">Mission #{mission.id}</span><strong>{mission.category_name}</strong>{!compact&&<p>{mission.description}</p>}<small>{new Date(mission.created_at).toLocaleDateString('fr-CA')} • {statusLabel[mission.status]||mission.status}</small></div><div className="mission-row-end">{mission.client_total_cents?<strong>{money(mission.client_total_cents)}</strong>:null}<span className={`portal-badge badge-${mission.status}`}>{statusLabel[mission.status]||mission.status}</span>{mission.status==='completed'&&<button className="portal-link" onClick={()=>onBilling(mission.id)}>Facture</button>}{mission.status==='completed'&&mission.payment_status!=='paid'&&onPay&&<button className="portal-link" onClick={()=>onPay(mission.id)}>Payer</button>}</div></article>}
function ActiveMission({mission,act}:{mission:Mission;act:(a:any)=>void}){const next=mission.status==='assigned'?['en-route','🚗 Je suis en route']:mission.status==='en_route'?['arrive','📍 Je suis arrivé']:mission.status==='arrived'?['start','▶️ Commencer la job']:mission.status==='in_progress'?['complete','✅ Terminer la job']:null;return <section className="portal-feature mission-live"><div className="feature-icon">{statusIcon[mission.status]||'🧭'}</div><div><span className="portal-kicker">Mission #{mission.id} • {mission.category_name||mission.category_id}</span><h2>{statusLabel[mission.status]||mission.status}</h2><p>{mission.description}</p><div className="mission-progress"><i className={['assigned','en_route','arrived','in_progress'].includes(mission.status)?'done':''}/><i className={['en_route','arrived','in_progress'].includes(mission.status)?'done':''}/><i className={['arrived','in_progress'].includes(mission.status)?'done':''}/><i className={mission.status==='in_progress'?'done':''}/></div></div>{next&&<button className="portal-primary" onClick={()=>act(next[0])}>{next[1]}</button>}</section>}
function ProfileCard({user,role}:{user:User;role:string}){return <section className="portal-panel profile-panel"><div className="profile-hero"><div className="profile-avatar">{user.name?.[0]?.toUpperCase()}</div><div><span className="portal-kicker">{role==='client'?'Compte client':'Compte partenaire'}</span><h2>{user.name}</h2><p>Compte actif FaisLaJob</p></div></div><div className="profile-lines"><div><span>Courriel</span><strong>{user.email}</strong></div><div><span>Téléphone</span><strong>{user.phone||'Non renseigné'}</strong></div><div><span>Type de compte</span><strong>{role==='client'?'Client':'Partenaire'}</strong></div></div></section>}
function BillingModal({billing,close,pay}:{billing:Billing;close:()=>void;pay:()=>void}){return <div className="portal-modal-bg" onClick={close}><div className="portal-modal" onClick={e=>e.stopPropagation()}><span className="portal-kicker">Facture mission #{billing.mission_id}</span><h2>{money(billing.client_total_cents)}</h2><div className="profile-lines"><div><span>Temps réel</span><strong>{billing.actual_minutes} min</strong></div><div><span>Temps facturé</span><strong>{billing.billable_minutes} min</strong></div><div><span>Service</span><strong>{money(billing.subtotal_cents)}</strong></div><div><span>Frais de service</span><strong>{money(billing.client_service_fee_cents)}</strong></div><div><span>Paiement</span><strong>{billing.payment_status||'pending'}</strong></div></div>{billing.payment_status!=='paid'&&<button className="portal-primary full" onClick={pay}>💳 Payer (test)</button>}<button className="portal-secondary full" onClick={close}>Fermer</button></div></div>}
