import Fastify from 'fastify';
import cors from '@fastify/cors';
import { createHash, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { createPool } from './db.js';

const pool = createPool();
const app = Fastify({ logger: true });
await app.register(cors, { origin: true, credentials: true });

const DEFAULT_HOURLY_RATE_CENTS = Number(process.env.DEFAULT_HOURLY_RATE_CENTS ?? 4000);
const MINIMUM_BILLABLE_MINUTES = Number(process.env.MINIMUM_BILLABLE_MINUTES ?? 15);
const CLIENT_SERVICE_FEE_BPS = Number(process.env.CLIENT_SERVICE_FEE_BPS ?? 1100);
const PROVIDER_COMMISSION_BPS = Number(process.env.PROVIDER_COMMISSION_BPS ?? 3000);
const PAYMENTS_MODE = process.env.PAYMENTS_MODE ?? 'mock';
const ADMIN_TOKEN = process.env.ADMIN_TOKEN ?? '';

const defaultCategories = [
  { id: 'menage', name: 'Ménage' },
  { id: 'reparations', name: 'Petites réparations' },
  { id: 'exterieur', name: 'Terrain & extérieur' },
  { id: 'demenagement', name: 'Déménagement' },
  { id: 'deneigement', name: 'Déneigement' },
  { id: 'animaux', name: 'Animaux' },
];

function hashPassword(password: string) { const salt = randomBytes(16); const key = scryptSync(password, salt, 64); return `${salt.toString('hex')}:${key.toString('hex')}`; }
function verifyPassword(password: string, stored: string) { const [saltHex,keyHex]=stored.split(':'); if(!saltHex||!keyHex)return false; const expected=Buffer.from(keyHex,'hex'); const actual=scryptSync(password,Buffer.from(saltHex,'hex'),expected.length); return expected.length===actual.length&&timingSafeEqual(expected,actual); }
function tokenHash(token:string){return createHash('sha256').update(token).digest('hex');}
function cookieValue(header:string|undefined,name:string){if(!header)return null;for(const part of header.split(';')){const[key,...rest]=part.trim().split('=');if(key===name)return decodeURIComponent(rest.join('='));}return null;}
function sessionCookie(token:string,maxAge:number){const secure=process.env.COOKIE_SECURE==='true'?'; Secure':'';return `faislajob_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${secure}`;}
async function currentUser(request:any){const token=cookieValue(request.headers.cookie,'faislajob_session');if(!token)return null;const r=await pool.query(`SELECT u.id,u.email,u.role,u.client_id,u.provider_id,COALESCE(c.name,p.name) name,COALESCE(c.phone,p.phone) phone FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN clients c ON c.id=u.client_id LEFT JOIN providers p ON p.id=u.provider_id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1`,[tokenHash(token)]);return r.rows[0]??null;}
async function requireRole(request:any,reply:any,role:'client'|'provider'){const user=await currentUser(request);if(!user){reply.code(401).send({error:'authentication required'});return null;}if(user.role!==role){reply.code(403).send({error:`${role} account required`});return null;}return user;}
function requireAdmin(request:any,reply:any){if(!ADMIN_TOKEN){reply.code(503).send({error:'ADMIN_TOKEN is not configured on the server'});return false;}const supplied=String(request.headers['x-admin-token']??'');const a=Buffer.from(supplied);const b=Buffer.from(ADMIN_TOKEN);if(a.length!==b.length||!timingSafeEqual(a,b)){reply.code(401).send({error:'admin authentication required'});return false;}return true;}
async function createSession(reply:any,userId:number){const token=randomBytes(32).toString('base64url');await pool.query(`INSERT INTO sessions(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 days')`,[userId,tokenHash(token)]);reply.header('Set-Cookie',sessionCookie(token,60*60*24*30));}

async function initializeDatabase(){
  await pool.query(`
    CREATE TABLE IF NOT EXISTS categories(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    ALTER TABLE categories ADD COLUMN IF NOT EXISTS hourly_rate_cents INTEGER;
    ALTER TABLE providers ADD COLUMN IF NOT EXISTS is_online BOOLEAN NOT NULL DEFAULT FALSE;
    ALTER TABLE providers ADD COLUMN IF NOT EXISTS last_online_at TIMESTAMPTZ;
    ALTER TABLE missions ADD COLUMN IF NOT EXISTS en_route_at TIMESTAMPTZ;
    ALTER TABLE missions ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMPTZ;
    ALTER TABLE missions ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
    ALTER TABLE missions ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
    ALTER TABLE missions ADD COLUMN IF NOT EXISTS duration_minutes INTEGER;
    ALTER TABLE payments ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'client_charge';
    ALTER TABLE payments ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
    ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_method TEXT;
    CREATE TABLE IF NOT EXISTS provider_categories(provider_id BIGINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,category_id TEXT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(provider_id,category_id));
    CREATE TABLE IF NOT EXISTS mission_offers(id BIGSERIAL PRIMARY KEY,mission_id BIGINT NOT NULL REFERENCES missions(id) ON DELETE CASCADE,provider_id BIGINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'pending',offered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),responded_at TIMESTAMPTZ,UNIQUE(mission_id,provider_id));
    CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('client','provider')),client_id BIGINT UNIQUE REFERENCES clients(id) ON DELETE CASCADE,provider_id BIGINT UNIQUE REFERENCES providers(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),CHECK((role='client' AND client_id IS NOT NULL AND provider_id IS NULL) OR (role='provider' AND provider_id IS NOT NULL AND client_id IS NULL)));
    CREATE TABLE IF NOT EXISTS sessions(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS mission_billing(mission_id BIGINT PRIMARY KEY REFERENCES missions(id) ON DELETE CASCADE,hourly_rate_cents INTEGER NOT NULL,actual_minutes INTEGER NOT NULL,billable_minutes INTEGER NOT NULL,subtotal_cents INTEGER NOT NULL,client_service_fee_bps INTEGER NOT NULL,client_service_fee_cents INTEGER NOT NULL,client_total_cents INTEGER NOT NULL,provider_commission_bps INTEGER NOT NULL,provider_commission_cents INTEGER NOT NULL,provider_net_cents INTEGER NOT NULL,currency TEXT NOT NULL DEFAULT 'CAD',status TEXT NOT NULL DEFAULT 'ready',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS provider_payouts(id BIGSERIAL PRIMARY KEY,mission_id BIGINT NOT NULL UNIQUE REFERENCES missions(id) ON DELETE CASCADE,provider_id BIGINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,amount_cents INTEGER NOT NULL,currency TEXT NOT NULL DEFAULT 'CAD',status TEXT NOT NULL DEFAULT 'waiting_payment',release_at TIMESTAMPTZ,paid_at TIMESTAMPTZ,external_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON sessions(expires_at);CREATE UNIQUE INDEX IF NOT EXISTS payments_mission_kind_idx ON payments(mission_id,kind);
  `);
  for(const c of defaultCategories)await pool.query(`INSERT INTO categories(id,name,hourly_rate_cents) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,hourly_rate_cents=COALESCE(categories.hourly_rate_cents,EXCLUDED.hourly_rate_cents)`,[c.id,c.name,DEFAULT_HOURLY_RATE_CENTS]);
  await pool.query(`DELETE FROM sessions WHERE expires_at<=NOW()`);
}

async function dispatchMission(missionId:number,categoryId:string){const providers=await pool.query(`SELECT p.id FROM providers p JOIN provider_categories pc ON pc.provider_id=p.id WHERE p.status='active' AND p.is_online=TRUE AND pc.category_id=$1`,[categoryId]);for(const p of providers.rows)await pool.query(`INSERT INTO mission_offers(mission_id,provider_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[missionId,p.id]);if(providers.rowCount)await pool.query(`UPDATE missions SET status='offered',updated_at=NOW() WHERE id=$1 AND provider_id IS NULL`,[missionId]);return providers.rowCount??0;}
async function finalizeBilling(missionId:number){const result=await pool.query(`SELECT m.id,m.provider_id,m.duration_minutes,c.hourly_rate_cents FROM missions m JOIN categories c ON c.id=m.category_id WHERE m.id=$1`,[missionId]);if(!result.rowCount)return null;const m=result.rows[0],actualMinutes=Math.max(1,Number(m.duration_minutes||1)),billableMinutes=Math.max(MINIMUM_BILLABLE_MINUTES,actualMinutes),hourlyRate=Number(m.hourly_rate_cents||DEFAULT_HOURLY_RATE_CENTS),subtotal=Math.ceil(hourlyRate*billableMinutes/60),serviceFee=Math.ceil(subtotal*CLIENT_SERVICE_FEE_BPS/10000),clientTotal=subtotal+serviceFee,commission=Math.ceil(subtotal*PROVIDER_COMMISSION_BPS/10000),providerNet=Math.max(0,subtotal-commission);await pool.query(`INSERT INTO mission_billing(mission_id,hourly_rate_cents,actual_minutes,billable_minutes,subtotal_cents,client_service_fee_bps,client_service_fee_cents,client_total_cents,provider_commission_bps,provider_commission_cents,provider_net_cents,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'ready') ON CONFLICT(mission_id) DO UPDATE SET hourly_rate_cents=EXCLUDED.hourly_rate_cents,actual_minutes=EXCLUDED.actual_minutes,billable_minutes=EXCLUDED.billable_minutes,subtotal_cents=EXCLUDED.subtotal_cents,client_service_fee_bps=EXCLUDED.client_service_fee_bps,client_service_fee_cents=EXCLUDED.client_service_fee_cents,client_total_cents=EXCLUDED.client_total_cents,provider_commission_bps=EXCLUDED.provider_commission_bps,provider_commission_cents=EXCLUDED.provider_commission_cents,provider_net_cents=EXCLUDED.provider_net_cents,updated_at=NOW()`,[missionId,hourlyRate,actualMinutes,billableMinutes,subtotal,CLIENT_SERVICE_FEE_BPS,serviceFee,clientTotal,PROVIDER_COMMISSION_BPS,commission,providerNet]);await pool.query(`INSERT INTO payments(mission_id,amount_cents,currency,status,provider,kind) VALUES($1,$2,'CAD','pending',$3,'client_charge') ON CONFLICT(mission_id,kind) DO UPDATE SET amount_cents=EXCLUDED.amount_cents,status=CASE WHEN payments.status='paid' THEN 'paid' ELSE 'pending' END,updated_at=NOW()`,[missionId,clientTotal,PAYMENTS_MODE]);if(m.provider_id)await pool.query(`INSERT INTO provider_payouts(mission_id,provider_id,amount_cents,status) VALUES($1,$2,$3,'waiting_payment') ON CONFLICT(mission_id) DO UPDATE SET provider_id=EXCLUDED.provider_id,amount_cents=EXCLUDED.amount_cents,updated_at=NOW()`,[missionId,m.provider_id,providerNet]);return(await pool.query(`SELECT b.*,p.status payment_status,p.payment_method,pp.status payout_status,pp.release_at FROM mission_billing b LEFT JOIN payments p ON p.mission_id=b.mission_id AND p.kind='client_charge' LEFT JOIN provider_payouts pp ON pp.mission_id=b.mission_id WHERE b.mission_id=$1`,[missionId])).rows[0];}

app.get('/health',async(_r,reply)=>{try{await pool.query('SELECT 1');return{ok:true,service:'faislajob-api',version:'0.9.0',database:'connected',paymentsMode:PAYMENTS_MODE,adminConfigured:Boolean(ADMIN_TOKEN)}}catch(e){app.log.error(e);return reply.code(503).send({ok:false,database:'disconnected'})}});
app.post('/api/auth/register',async(request,reply)=>{const b=request.body as any,name=b?.name?.trim(),email=b?.email?.trim().toLowerCase(),phone=b?.phone?.trim()||null,password=b?.password||'',role=b?.role;if(!name||!email||!['client','provider'].includes(role||''))return reply.code(400).send({error:'name, email and valid role are required'});if(password.length<8)return reply.code(400).send({error:'password must contain at least 8 characters'});if((await pool.query('SELECT id FROM users WHERE email=$1',[email])).rowCount)return reply.code(409).send({error:'an account already exists with this email'});const c=await pool.connect();try{await c.query('BEGIN');let profileId:number;if(role==='client'){const x=await c.query('SELECT id FROM clients WHERE LOWER(email)=$1 LIMIT 1',[email]);profileId=x.rowCount?Number(x.rows[0].id):Number((await c.query('INSERT INTO clients(name,email,phone) VALUES($1,$2,$3) RETURNING id',[name,email,phone])).rows[0].id);if(x.rowCount)await c.query('UPDATE clients SET name=$1,phone=$2,updated_at=NOW() WHERE id=$3',[name,phone,profileId]);}else{const x=await c.query('SELECT id FROM providers WHERE LOWER(email)=$1 LIMIT 1',[email]);profileId=x.rowCount?Number(x.rows[0].id):Number((await c.query(`INSERT INTO providers(name,email,phone,status) VALUES($1,$2,$3,'active') RETURNING id`,[name,email,phone])).rows[0].id);if(x.rowCount)await c.query(`UPDATE providers SET name=$1,phone=$2,status='active',updated_at=NOW() WHERE id=$3`,[name,phone,profileId]);}const u=(await c.query(`INSERT INTO users(email,password_hash,role,client_id,provider_id) VALUES($1,$2,$3,$4,$5) RETURNING id,email,role,client_id,provider_id`,[email,hashPassword(password),role,role==='client'?profileId:null,role==='provider'?profileId:null])).rows[0];await c.query('COMMIT');await createSession(reply,Number(u.id));return reply.code(201).send({user:{...u,name,phone}});}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}});
app.post('/api/auth/login',async(request,reply)=>{const b=request.body as any,email=b?.email?.trim().toLowerCase();if(!email||!b?.password)return reply.code(400).send({error:'email and password are required'});const r=await pool.query(`SELECT u.id,u.email,u.password_hash,u.role,u.client_id,u.provider_id,COALESCE(c.name,p.name) name,COALESCE(c.phone,p.phone) phone FROM users u LEFT JOIN clients c ON c.id=u.client_id LEFT JOIN providers p ON p.id=u.provider_id WHERE u.email=$1 LIMIT 1`,[email]);const u=r.rows[0];if(!u||!verifyPassword(b.password,u.password_hash))return reply.code(401).send({error:'invalid email or password'});await createSession(reply,Number(u.id));delete u.password_hash;return{user:u}});
app.post('/api/auth/logout',async(request,reply)=>{const token=cookieValue(request.headers.cookie,'faislajob_session');if(token)await pool.query('DELETE FROM sessions WHERE token_hash=$1',[tokenHash(token)]);reply.header('Set-Cookie',sessionCookie('',0));return{ok:true}});
app.get('/api/auth/me',async(request,reply)=>{const u=await currentUser(request);if(!u)return reply.code(401).send({error:'not authenticated'});return{user:u}});

app.get('/api/categories',async()=>({categories:(await pool.query('SELECT id,name,hourly_rate_cents FROM categories ORDER BY name')).rows}));
app.post('/api/clients',async(request,reply)=>{const b=request.body as any;if(!b?.name?.trim())return reply.code(400).send({error:'name is required'});const email=b.email?.trim().toLowerCase()||null;if(email){const e=await pool.query('SELECT * FROM clients WHERE LOWER(email)=$1 LIMIT 1',[email]);if(e.rowCount)return{client:e.rows[0],existing:true}}const r=await pool.query(`INSERT INTO clients(name,email,phone) VALUES($1,$2,$3) RETURNING id,name,email,phone,created_at`,[b.name.trim(),email,b.phone?.trim()||null]);return reply.code(201).send({client:r.rows[0],existing:false})});
app.get('/api/providers/:id',async(request,reply)=>{const{id}=request.params as any,u=await requireRole(request,reply,'provider');if(!u)return;if(String(u.provider_id)!==String(id))return reply.code(403).send({error:'forbidden'});const r=await pool.query('SELECT * FROM providers WHERE id=$1',[id]);if(!r.rowCount)return reply.code(404).send({error:'provider not found'});return{provider:r.rows[0]}});
app.post('/api/providers/:id/availability',async(request,reply)=>{const{id}=request.params as any,u=await requireRole(request,reply,'provider');if(!u)return;if(String(u.provider_id)!==String(id))return reply.code(403).send({error:'forbidden'});const b=request.body as any;if(typeof b?.online!=='boolean')return reply.code(400).send({error:'online boolean is required'});await pool.query(`UPDATE providers SET is_online=$1,last_online_at=CASE WHEN $1 THEN NOW() ELSE last_online_at END,updated_at=NOW() WHERE id=$2`,[b.online,id]);if(Array.isArray(b.categoryIds)){await pool.query('DELETE FROM provider_categories WHERE provider_id=$1',[id]);for(const x of b.categoryIds)await pool.query(`INSERT INTO provider_categories(provider_id,category_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[id,x])}return{provider:(await pool.query(`SELECT p.id,p.name,p.status,p.is_online,COALESCE(array_agg(pc.category_id) FILTER(WHERE pc.category_id IS NOT NULL),'{}') category_ids FROM providers p LEFT JOIN provider_categories pc ON pc.provider_id=p.id WHERE p.id=$1 GROUP BY p.id`,[id])).rows[0]}});
app.get('/api/providers/:id/offers',async(request,reply)=>{const{id}=request.params as any,u=await requireRole(request,reply,'provider');if(!u)return;if(String(u.provider_id)!==String(id))return reply.code(403).send({error:'forbidden'});return{offers:(await pool.query(`SELECT o.id offer_id,o.status offer_status,o.offered_at,m.id mission_id,m.category_id,c.name category_name,m.description,m.scheduled_at,m.status mission_status FROM mission_offers o JOIN missions m ON m.id=o.mission_id LEFT JOIN categories c ON c.id=m.category_id WHERE o.provider_id=$1 AND o.status='pending' AND m.provider_id IS NULL ORDER BY o.offered_at`,[id])).rows}});
app.post('/api/missions',async(request,reply)=>{const b=request.body as any,u=await currentUser(request),clientId=u?.role==='client'?Number(u.client_id):Number(b?.clientId||0);if(!clientId||!b?.categoryId)return reply.code(400).send({error:'clientId and categoryId are required'});const r=await pool.query(`INSERT INTO missions(client_id,category_id,description,scheduled_at) VALUES($1,$2,$3,$4) RETURNING *`,[clientId,b.categoryId,b.description?.trim()||null,b.scheduledAt||null]);const offersCreated=await dispatchMission(Number(r.rows[0].id),b.categoryId);return reply.code(201).send({mission:(await pool.query('SELECT * FROM missions WHERE id=$1',[r.rows[0].id])).rows[0],dispatch:{offersCreated}})});
app.get('/api/missions/:id',async(request,reply)=>{const{id}=request.params as any,u=await currentUser(request),r=await pool.query(`SELECT m.*,c.name category_name,c.hourly_rate_cents FROM missions m LEFT JOIN categories c ON c.id=m.category_id WHERE m.id=$1`,[id]);if(!r.rowCount)return reply.code(404).send({error:'mission not found'});const m=r.rows[0];if(u?.role==='client'&&String(m.client_id)!==String(u.client_id))return reply.code(403).send({error:'forbidden'});if(u?.role==='provider'&&String(m.provider_id)!==String(u.provider_id))return reply.code(403).send({error:'forbidden'});return{mission:m}});
app.get('/api/client/missions',async(request,reply)=>{const u=await requireRole(request,reply,'client');if(!u)return;return{missions:(await pool.query(`SELECT m.id,m.category_id,c.name category_name,m.status,m.description,m.duration_minutes,m.created_at,m.completed_at,b.client_total_cents,b.billable_minutes,b.status billing_status,p.status payment_status FROM missions m LEFT JOIN categories c ON c.id=m.category_id LEFT JOIN mission_billing b ON b.mission_id=m.id LEFT JOIN payments p ON p.mission_id=m.id AND p.kind='client_charge' WHERE m.client_id=$1 ORDER BY m.created_at DESC`,[u.client_id])).rows}});
app.post('/api/offers/:offerId/accept',async(request,reply)=>{const u=await requireRole(request,reply,'provider');if(!u)return;const{offerId}=request.params as any,c=await pool.connect();try{await c.query('BEGIN');const o=await c.query(`SELECT id,mission_id,provider_id FROM mission_offers WHERE id=$1 AND provider_id=$2 AND status='pending' FOR UPDATE`,[offerId,u.provider_id]);if(!o.rowCount){await c.query('ROLLBACK');return reply.code(404).send({error:'pending offer not found'})}const x=o.rows[0],m=await c.query(`UPDATE missions SET provider_id=$1,status='assigned',updated_at=NOW() WHERE id=$2 AND provider_id IS NULL RETURNING *`,[x.provider_id,x.mission_id]);if(!m.rowCount){await c.query(`UPDATE mission_offers SET status='expired',responded_at=NOW() WHERE id=$1`,[offerId]);await c.query('COMMIT');return reply.code(409).send({error:'mission already taken'})}await c.query(`UPDATE mission_offers SET status=CASE WHEN id=$1 THEN 'accepted' ELSE 'expired' END,responded_at=NOW() WHERE mission_id=$2`,[offerId,x.mission_id]);await c.query('COMMIT');return{mission:m.rows[0]}}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}});
app.post('/api/offers/:offerId/decline',async(request,reply)=>{const u=await requireRole(request,reply,'provider');if(!u)return;const{offerId}=request.params as any,r=await pool.query(`UPDATE mission_offers SET status='declined',responded_at=NOW() WHERE id=$1 AND provider_id=$2 AND status='pending' RETURNING *`,[offerId,u.provider_id]);if(!r.rowCount)return reply.code(404).send({error:'pending offer not found'});return{offer:r.rows[0]}});
async function transitionMission(request:any,reply:any,from:string[],to:string,col:string){const u=await requireRole(request,reply,'provider');if(!u)return;const{id}=request.params as any,r=await pool.query(`UPDATE missions SET status=$1,${col}=NOW(),updated_at=NOW() WHERE id=$2 AND provider_id=$3 AND status=ANY($4::text[]) RETURNING *`,[to,id,u.provider_id,from]);if(!r.rowCount)return reply.code(409).send({error:`mission cannot transition to ${to}`});return{mission:r.rows[0]}}
app.post('/api/missions/:id/en-route',async(r,p)=>transitionMission(r,p,['assigned'],'en_route','en_route_at'));app.post('/api/missions/:id/arrive',async(r,p)=>transitionMission(r,p,['en_route'],'arrived','arrived_at'));app.post('/api/missions/:id/start',async(r,p)=>transitionMission(r,p,['arrived'],'in_progress','started_at'));
app.post('/api/missions/:id/complete',async(request,reply)=>{const u=await requireRole(request,reply,'provider');if(!u)return;const{id}=request.params as any,r=await pool.query(`UPDATE missions SET status='completed',completed_at=NOW(),duration_minutes=GREATEST(1,CEIL(EXTRACT(EPOCH FROM(NOW()-started_at))/60)::int),updated_at=NOW() WHERE id=$1 AND provider_id=$2 AND status='in_progress' AND started_at IS NOT NULL RETURNING *`,[id,u.provider_id]);if(!r.rowCount)return reply.code(409).send({error:'mission cannot be completed'});return{mission:r.rows[0],billing:await finalizeBilling(Number(id))}});
app.get('/api/missions/:id/billing',async(request,reply)=>{const{id}=request.params as any,u=await currentUser(request);if(!u)return reply.code(401).send({error:'authentication required'});const m=await pool.query('SELECT client_id,provider_id,status FROM missions WHERE id=$1',[id]);if(!m.rowCount)return reply.code(404).send({error:'mission not found'});const row=m.rows[0];if(u.role==='client'&&String(row.client_id)!==String(u.client_id))return reply.code(403).send({error:'forbidden'});if(u.role==='provider'&&String(row.provider_id)!==String(u.provider_id))return reply.code(403).send({error:'forbidden'});if(row.status==='completed'&&!(await pool.query('SELECT 1 FROM mission_billing WHERE mission_id=$1',[id])).rowCount)await finalizeBilling(Number(id));const r=await pool.query(`SELECT b.*,p.status payment_status,p.payment_method,p.paid_at,pp.status payout_status,pp.release_at,pp.paid_at payout_paid_at FROM mission_billing b LEFT JOIN payments p ON p.mission_id=b.mission_id AND p.kind='client_charge' LEFT JOIN provider_payouts pp ON pp.mission_id=b.mission_id WHERE b.mission_id=$1`,[id]);if(!r.rowCount)return reply.code(409).send({error:'billing is not ready yet'});return{billing:r.rows[0],paymentsMode:PAYMENTS_MODE}});
app.post('/api/missions/:id/pay/mock',async(request,reply)=>{if(PAYMENTS_MODE==='live')return reply.code(404).send({error:'mock payments disabled'});const u=await requireRole(request,reply,'client');if(!u)return;const{id}=request.params as any,m=await pool.query(`SELECT id,status FROM missions WHERE id=$1 AND client_id=$2`,[id,u.client_id]);if(!m.rowCount)return reply.code(404).send({error:'mission not found'});if(m.rows[0].status!=='completed')return reply.code(409).send({error:'mission must be completed before payment'});const b=await finalizeBilling(Number(id));if(!b)return reply.code(409).send({error:'billing unavailable'});await pool.query(`UPDATE payments SET status='paid',payment_method='mock',provider='mock',paid_at=NOW(),updated_at=NOW() WHERE mission_id=$1 AND kind='client_charge'`,[id]);await pool.query(`UPDATE mission_billing SET status='paid',updated_at=NOW() WHERE mission_id=$1`,[id]);await pool.query(`UPDATE provider_payouts SET status='holding',release_at=NOW()+INTERVAL '7 days',updated_at=NOW() WHERE mission_id=$1`,[id]);return{billing:(await pool.query(`SELECT b.*,p.status payment_status,p.payment_method,p.paid_at,pp.status payout_status,pp.release_at FROM mission_billing b LEFT JOIN payments p ON p.mission_id=b.mission_id AND p.kind='client_charge' LEFT JOIN provider_payouts pp ON pp.mission_id=b.mission_id WHERE b.mission_id=$1`,[id])).rows[0],mock:true}});
app.get('/api/provider/payouts',async(request,reply)=>{const u=await requireRole(request,reply,'provider');if(!u)return;return{payouts:(await pool.query(`SELECT pp.*,m.category_id,c.name category_name,m.duration_minutes FROM provider_payouts pp JOIN missions m ON m.id=pp.mission_id LEFT JOIN categories c ON c.id=m.category_id WHERE pp.provider_id=$1 ORDER BY pp.created_at DESC`,[u.provider_id])).rows}});

// ADMIN / DISPATCH
app.get('/api/admin/overview',async(request,reply)=>{if(!requireAdmin(request,reply))return;const [missions,clients,providers,revenue,pending]=await Promise.all([pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status NOT IN('completed','cancelled'))::int active,COUNT(*) FILTER(WHERE status='offered')::int offered,COUNT(*) FILTER(WHERE status='in_progress')::int in_progress FROM missions`),pool.query(`SELECT COUNT(*)::int total FROM clients`),pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE is_online)::int online,COUNT(*) FILTER(WHERE status='active')::int active FROM providers`),pool.query(`SELECT COALESCE(SUM(client_total_cents),0)::int total FROM mission_billing WHERE status='paid'`),pool.query(`SELECT COALESCE(SUM(amount_cents),0)::int total FROM provider_payouts WHERE status IN('waiting_payment','holding','ready')`)]);return{missions:missions.rows[0],clients:clients.rows[0],providers:providers.rows[0],revenue_cents:revenue.rows[0].total,pending_payouts_cents:pending.rows[0].total}});
app.get('/api/admin/missions',async(request,reply)=>{if(!requireAdmin(request,reply))return;const q=request.query as any,search=String(q?.search||'').trim(),status=String(q?.status||'').trim();const r=await pool.query(`SELECT m.*,c.name category_name,cl.name client_name,cl.phone client_phone,cl.email client_email,p.name provider_name,p.phone provider_phone,b.client_total_cents,b.provider_net_cents,pay.status payment_status FROM missions m LEFT JOIN categories c ON c.id=m.category_id LEFT JOIN clients cl ON cl.id=m.client_id LEFT JOIN providers p ON p.id=m.provider_id LEFT JOIN mission_billing b ON b.mission_id=m.id LEFT JOIN payments pay ON pay.mission_id=m.id AND pay.kind='client_charge' WHERE ($1='' OR m.status=$1) AND ($2='' OR CAST(m.id AS TEXT) ILIKE '%'||$2||'%' OR cl.name ILIKE '%'||$2||'%' OR COALESCE(p.name,'') ILIKE '%'||$2||'%' OR COALESCE(cl.phone,'') ILIKE '%'||$2||'%') ORDER BY m.created_at DESC LIMIT 200`,[status,search]);return{missions:r.rows}});
app.get('/api/admin/clients',async(request,reply)=>{if(!requireAdmin(request,reply))return;const q=String((request.query as any)?.search||'').trim();return{clients:(await pool.query(`SELECT c.*,COUNT(m.id)::int missions_count,MAX(m.created_at) last_mission_at FROM clients c LEFT JOIN missions m ON m.client_id=c.id WHERE $1='' OR c.name ILIKE '%'||$1||'%' OR COALESCE(c.email,'') ILIKE '%'||$1||'%' OR COALESCE(c.phone,'') ILIKE '%'||$1||'%' GROUP BY c.id ORDER BY c.created_at DESC LIMIT 200`,[q])).rows}});
app.get('/api/admin/providers',async(request,reply)=>{if(!requireAdmin(request,reply))return;const q=String((request.query as any)?.search||'').trim();return{providers:(await pool.query(`SELECT p.*,COALESCE(array_agg(DISTINCT pc.category_id) FILTER(WHERE pc.category_id IS NOT NULL),'{}') category_ids,COUNT(DISTINCT m.id) FILTER(WHERE m.status='completed')::int completed_missions,COUNT(DISTINCT m.id) FILTER(WHERE m.status NOT IN('completed','cancelled'))::int active_missions FROM providers p LEFT JOIN provider_categories pc ON pc.provider_id=p.id LEFT JOIN missions m ON m.provider_id=p.id WHERE $1='' OR p.name ILIKE '%'||$1||'%' OR COALESCE(p.email,'') ILIKE '%'||$1||'%' OR COALESCE(p.phone,'') ILIKE '%'||$1||'%' GROUP BY p.id ORDER BY p.is_online DESC,p.created_at DESC LIMIT 200`,[q])).rows}});
app.get('/api/admin/finance',async(request,reply)=>{if(!requireAdmin(request,reply))return;const payments=await pool.query(`SELECT pay.*,m.client_id,cl.name client_name,c.name category_name FROM payments pay JOIN missions m ON m.id=pay.mission_id LEFT JOIN clients cl ON cl.id=m.client_id LEFT JOIN categories c ON c.id=m.category_id ORDER BY pay.created_at DESC LIMIT 200`);const payouts=await pool.query(`SELECT pp.*,p.name provider_name,c.name category_name FROM provider_payouts pp JOIN providers p ON p.id=pp.provider_id JOIN missions m ON m.id=pp.mission_id LEFT JOIN categories c ON c.id=m.category_id ORDER BY pp.created_at DESC LIMIT 200`);return{payments:payments.rows,payouts:payouts.rows}});
app.post('/api/admin/missions/:id/assign',async(request,reply)=>{if(!requireAdmin(request,reply))return;const{id}=request.params as any,b=request.body as any,providerId=Number(b?.providerId);if(!providerId)return reply.code(400).send({error:'providerId is required'});const p=await pool.query(`SELECT id FROM providers WHERE id=$1 AND status='active'`,[providerId]);if(!p.rowCount)return reply.code(404).send({error:'active provider not found'});const r=await pool.query(`UPDATE missions SET provider_id=$1,status='assigned',updated_at=NOW() WHERE id=$2 AND status NOT IN('completed','cancelled') RETURNING *`,[providerId,id]);if(!r.rowCount)return reply.code(409).send({error:'mission cannot be assigned'});await pool.query(`UPDATE mission_offers SET status=CASE WHEN provider_id=$1 THEN 'accepted' ELSE 'expired' END,responded_at=NOW() WHERE mission_id=$2`,[providerId,id]);return{mission:r.rows[0]}});
app.post('/api/admin/missions/:id/redispatch',async(request,reply)=>{if(!requireAdmin(request,reply))return;const{id}=request.params as any,m=await pool.query(`SELECT category_id FROM missions WHERE id=$1 AND status NOT IN('completed','cancelled')`,[id]);if(!m.rowCount)return reply.code(404).send({error:'mission not found'});await pool.query(`UPDATE missions SET provider_id=NULL,status='requested',updated_at=NOW() WHERE id=$1`,[id]);await pool.query(`UPDATE mission_offers SET status='expired',responded_at=NOW() WHERE mission_id=$1 AND status='pending'`,[id]);const offersCreated=await dispatchMission(Number(id),m.rows[0].category_id);return{ok:true,offersCreated}});
app.post('/api/admin/missions/:id/cancel',async(request,reply)=>{if(!requireAdmin(request,reply))return;const{id}=request.params as any,r=await pool.query(`UPDATE missions SET status='cancelled',updated_at=NOW() WHERE id=$1 AND status NOT IN('completed','cancelled') RETURNING *`,[id]);if(!r.rowCount)return reply.code(409).send({error:'mission cannot be cancelled'});await pool.query(`UPDATE mission_offers SET status='expired',responded_at=NOW() WHERE mission_id=$1 AND status='pending'`,[id]);return{mission:r.rows[0]}});
app.post('/api/admin/providers/:id/status',async(request,reply)=>{if(!requireAdmin(request,reply))return;const{id}=request.params as any,b=request.body as any,status=String(b?.status||'');if(!['active','suspended','inactive'].includes(status))return reply.code(400).send({error:'invalid status'});const r=await pool.query(`UPDATE providers SET status=$1,is_online=CASE WHEN $1='active' THEN is_online ELSE FALSE END,updated_at=NOW() WHERE id=$2 RETURNING *`,[status,id]);if(!r.rowCount)return reply.code(404).send({error:'provider not found'});return{provider:r.rows[0]}});
app.post('/api/admin/providers/:id/online',async(request,reply)=>{if(!requireAdmin(request,reply))return;const{id}=request.params as any,b=request.body as any;if(typeof b?.online!=='boolean')return reply.code(400).send({error:'online boolean is required'});const r=await pool.query(`UPDATE providers SET is_online=$1,last_online_at=CASE WHEN $1 THEN NOW() ELSE last_online_at END,updated_at=NOW() WHERE id=$2 AND status='active' RETURNING *`,[b.online,id]);if(!r.rowCount)return reply.code(409).send({error:'provider must be active'});return{provider:r.rows[0]}});
app.post('/api/admin/payouts/:id/status',async(request,reply)=>{if(!requireAdmin(request,reply))return;const{id}=request.params as any,b=request.body as any,status=String(b?.status||'');if(!['waiting_payment','holding','ready','paid','blocked'].includes(status))return reply.code(400).send({error:'invalid payout status'});const r=await pool.query(`UPDATE provider_payouts SET status=$1,paid_at=CASE WHEN $1='paid' THEN NOW() ELSE paid_at END,updated_at=NOW() WHERE id=$2 RETURNING *`,[status,id]);if(!r.rowCount)return reply.code(404).send({error:'payout not found'});return{payout:r.rows[0]}});

app.addHook('onClose',async()=>{await pool.end()});const port=Number(process.env.PORT??3000),host=process.env.HOST??'0.0.0.0';initializeDatabase().then(()=>app.listen({port,host})).catch(error=>{app.log.error(error);process.exit(1)});
